import { createContext, useContext, useState } from 'react'

export const LANGS = [
  { code: 'en', label: 'En', flag: '🇬🇧' },
  { code: 'ru', label: 'Ru', flag: '🇷🇺' },
  { code: 'kz', label: 'Kz', flag: '🇰🇿' },
]

const translations = {
  en: {
    // Tabs
    transactions: 'Transactions',
    budget: 'Budget',
    analytics: 'Analytics',
    calendar: 'Calendar',
    users: 'Users',
    invoices: 'Invoices',
    taxes: 'Taxes',
    payroll: 'Payroll',
    taxesSubtitle: 'Tax estimate and upcoming filing deadlines',
    payrollSubtitle: 'Salary deductions and total employee cost calculator',
    // Sidebar
    totalBalance: 'Total amount on accounts',
    myAccounts: 'My accounts',
    signOut: 'Sign out',
    business: 'Business',
    personal: 'Personal',
    // Actions
    income: 'Income',
    expense: 'Expense',
    transfer: 'Transfer',
    addIncome: '+ Income',
    addExpense: '− Expense',
    addTransfer: '⇄ Transfer',
    // Transactions
    description: 'Description',
    category: 'Category',
    account: 'Account',
    date: 'Date',
    amount: 'Amount',
    week: 'Week',
    month: 'Month',
    quarter: 'Quarter',
    year: 'Year',
    allTime: 'All time',
    all: 'All',
    search: 'Search...',
    profit: 'Profit',
    noTransactions: 'No transactions found',
    noTransactionsSub: 'Try changing the filter or add a transaction',
    comment: 'Comment',
    // Analytics
    cashFlow: 'Cash Flow',
    totalIncome: 'Total Income',
    totalExpenses: 'Total Expenses',
    netProfit: 'Net Profit',
    incomeVsExpenses: 'Income vs Expenses',
    profitTrend: 'Profit Trend',
    topCategories: 'Top Expense Categories',
    months3: '3 months',
    months6: '6 months',
    months12: '12 months',
    // Calendar
    today: 'Today',
    noData: 'No transactions',
    weekDays: ['Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa', 'Su'],
    // Users
    teamMembers: 'Team Members',
    inviteUser: 'Invite member',
    owner: 'Owner',
    admin: 'Admin',
    member: 'Member',
    inviteSent: 'Invite sent!',
    emailPlaceholder: 'colleague@company.com',
    role: 'Role',
    joined: 'Joined',
    pendingInvite: 'Pending invite',
    // Invoices
    createInvoice: 'New Invoice',
    invoiceNumber: 'Invoice #',
    client: 'Client',
    status: 'Status',
    issueDate: 'Issue Date',
    dueDate: 'Due Date',
    total: 'Total',
    paid: 'Paid',
    pending: 'Pending',
    overdue: 'Overdue',
    draft: 'Draft',
    allStatuses: 'All statuses',
    noInvoices: 'No invoices yet',
    noInvoicesSub: 'Create your first invoice',
    // Modal add
    addTitle: { income: 'Add Income', expense: 'Add Expense', transfer: 'Transfer' },
    saving: 'Saving...',
    from: 'From account',
    to: 'To account',
    optionalNote: 'Optional note',
    // Categories
    categories: 'Categories',
    addCategory: 'Add Category',
    editCategory: 'Edit Category',
    categoryName: 'Category name',
    categoryType: 'Type',
    categoryColor: 'Color',
    categoryIcon: 'Icon',
    noCategories: 'No categories yet',
    noCategoriesSub: 'Add your first category',
    deleteCategory: 'Delete',
    incomeCategories: 'Income',
    expenseCategories: 'Expense',
    bothCategories: 'Both',
    // Reports
    reports: 'Reports',
    reportPeriod: 'Period',
    exportCsv: 'Export CSV',
    exportPdf: 'Print / PDF',
    reportSummary: 'Summary',
    reportByCategory: 'By Category',
    reportIncome: 'Income',
    reportExpense: 'Expenses',
    reportProfit: 'Net Profit',
    reportTxCount: 'Transactions',
    dateFrom: 'From',
    dateTo: 'To',
    noReportData: 'No data for selected period',
    // Settings
    settings: 'Settings',
    profile: 'Profile',
    displayName: 'Display Name',
    emailAddress: 'Email',
    defaultCurrency: 'Default Currency',
    timezone: 'Timezone',
    dateFormat: 'Date Format',
    saveSettings: 'Save Settings',
    settingsSaved: 'Settings saved!',
    preferences: 'Preferences',
    // Invoice detail/print
    invoiceDetail: 'Invoice',
    printInvoice: 'Print',
    invoiceTo: 'Bill To',
    invoiceFrom: 'From',
    invoiceDesc: 'Description',
    invoiceSubtotal: 'Subtotal',
    invoiceTotal: 'Total',
    // AI Analytics
    aiAnalytics: 'AI',
    aiInsights: 'AI Insights',
    aiInsightsSub: 'Based on your transaction history',
    aiAssistant: 'AI Financial Assistant',
    aiPoweredBy: 'Powered by tencent/hy3-preview',
    aiAskPlaceholder: 'Ask about your finances...',
    noInsights: 'Add more transactions to get insights',
    aiWelcome: 'Hi! I\'m your AI financial assistant. Ask me anything about your finances, or try one of the prompts below.',
    // Common UI
    cancel: 'Cancel',
    other: 'Other',
    language: 'Language',
    dangerZone: 'Danger Zone',
    deleteAccount: 'Delete Account',
    deleteAccountDesc: 'Permanently delete your account and all data. This cannot be undone.',
    teamInfo: 'Members can view and add transactions. Admins have full access except managing the team.',
    // Reports periods
    thisMonth: 'This month',
    lastMonth: 'Last month',
    thisQuarter: 'This quarter',
    thisYear: 'This year',
    custom: 'Custom',
    dailyBreakdown: 'Daily Breakdown',
    // Add transaction modal
    selectAccount: 'Select account',
    noCategory: 'No category',
    errValidAmount: 'Please enter a valid amount',
    errSelectAccount: 'Please select an account',
    errSelectDestAccount: 'Please select the destination account',
    errDiffAccounts: 'Source and destination accounts must be different',
    errSomethingWrong: 'Something went wrong',
    errNameRequired: 'Name is required',
    // Invoice form
    currency: 'Currency',
    clientRequired: 'Client name is required',
    validAmount: 'Enter a valid amount',
    servicesRendered: 'Services rendered',
    yourCompany: 'Your Company',
  },

  ru: {
    transactions: 'Транзакции',
    budget: 'Бюджет',
    analytics: 'Аналитика',
    calendar: 'Календарь',
    users: 'Пользователи',
    invoices: 'Счета',
    taxes: 'Налоги',
    payroll: 'Зарплата',
    taxesSubtitle: 'Расчёт налогов и ближайшие сроки сдачи',
    payrollSubtitle: 'Калькулятор начислений, удержаний и полной стоимости сотрудника',
    totalBalance: 'Сумма на счетах',
    myAccounts: 'Мои счета',
    signOut: 'Выйти',
    business: 'Бизнес',
    personal: 'Физ. лицо',
    income: 'Доход',
    expense: 'Расход',
    transfer: 'Перевод',
    addIncome: '+ Доход',
    addExpense: '− Расход',
    addTransfer: '⇄ Перевод',
    description: 'Описание',
    category: 'Категория',
    account: 'Счёт',
    date: 'Дата',
    amount: 'Сумма',
    week: 'Неделя',
    month: 'Месяц',
    quarter: 'Квартал',
    year: 'Год',
    allTime: 'Всё время',
    all: 'Все',
    search: 'Поиск...',
    profit: 'Прибыль',
    noTransactions: 'Транзакции не найдены',
    noTransactionsSub: 'Измените фильтр или добавьте транзакцию',
    comment: 'Комментарий',
    cashFlow: 'Денежный поток',
    totalIncome: 'Общий доход',
    totalExpenses: 'Общие расходы',
    netProfit: 'Чистая прибыль',
    incomeVsExpenses: 'Доходы и расходы',
    profitTrend: 'Динамика прибыли',
    topCategories: 'Топ категорий расходов',
    months3: '3 месяца',
    months6: '6 месяцев',
    months12: '12 месяцев',
    today: 'Сегодня',
    noData: 'Нет транзакций',
    weekDays: ['Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб', 'Вс'],
    teamMembers: 'Участники команды',
    inviteUser: 'Пригласить',
    owner: 'Владелец',
    admin: 'Администратор',
    member: 'Участник',
    inviteSent: 'Приглашение отправлено!',
    emailPlaceholder: 'коллега@компания.com',
    role: 'Роль',
    joined: 'Вступил',
    pendingInvite: 'Ожидает принятия',
    createInvoice: 'Новый счёт',
    invoiceNumber: 'Счёт №',
    client: 'Клиент',
    status: 'Статус',
    issueDate: 'Дата выставления',
    dueDate: 'Срок оплаты',
    total: 'Сумма',
    paid: 'Оплачен',
    pending: 'Ожидает',
    overdue: 'Просрочен',
    draft: 'Черновик',
    allStatuses: 'Все статусы',
    noInvoices: 'Счетов пока нет',
    noInvoicesSub: 'Создайте первый счёт',
    addTitle: { income: 'Добавить доход', expense: 'Добавить расход', transfer: 'Перевод' },
    saving: 'Сохранение...',
    from: 'Со счёта',
    to: 'На счёт',
    optionalNote: 'Необязательный комментарий',
    categories: 'Категории',
    addCategory: 'Добавить категорию',
    editCategory: 'Редактировать',
    categoryName: 'Название',
    categoryType: 'Тип',
    categoryColor: 'Цвет',
    categoryIcon: 'Иконка',
    noCategories: 'Нет категорий',
    noCategoriesSub: 'Добавьте первую категорию',
    deleteCategory: 'Удалить',
    incomeCategories: 'Доходы',
    expenseCategories: 'Расходы',
    bothCategories: 'Оба',
    reports: 'Отчёты',
    reportPeriod: 'Период',
    exportCsv: 'Экспорт CSV',
    exportPdf: 'Печать / PDF',
    reportSummary: 'Сводка',
    reportByCategory: 'По категориям',
    reportIncome: 'Доход',
    reportExpense: 'Расходы',
    reportProfit: 'Чистая прибыль',
    reportTxCount: 'Транзакции',
    dateFrom: 'С',
    dateTo: 'По',
    noReportData: 'Нет данных за выбранный период',
    settings: 'Настройки',
    profile: 'Профиль',
    displayName: 'Имя',
    emailAddress: 'Email',
    defaultCurrency: 'Валюта по умолчанию',
    timezone: 'Часовой пояс',
    dateFormat: 'Формат даты',
    saveSettings: 'Сохранить',
    settingsSaved: 'Настройки сохранены!',
    preferences: 'Предпочтения',
    invoiceDetail: 'Счёт',
    printInvoice: 'Печать',
    invoiceTo: 'Получатель',
    invoiceFrom: 'От кого',
    invoiceDesc: 'Описание',
    invoiceSubtotal: 'Подытог',
    invoiceTotal: 'Итого',
    // AI Analytics
    aiAnalytics: 'AI',
    aiInsights: 'AI Инсайты',
    aiInsightsSub: 'На основе истории транзакций',
    aiAssistant: 'AI Финансовый ассистент',
    aiPoweredBy: 'На базе tencent/hy3-preview',
    aiAskPlaceholder: 'Спросите о ваших финансах...',
    noInsights: 'Добавьте больше транзакций для получения инсайтов',
    aiWelcome: 'Привет! Я ваш AI финансовый ассистент. Задайте любой вопрос о финансах или выберите подсказку ниже.',
    // Common UI
    cancel: 'Отмена',
    other: 'Другое',
    language: 'Язык',
    dangerZone: 'Опасная зона',
    deleteAccount: 'Удалить аккаунт',
    deleteAccountDesc: 'Безвозвратно удалить аккаунт и все данные. Это действие необратимо.',
    teamInfo: 'Участники могут просматривать и добавлять транзакции. Администраторы имеют полный доступ, кроме управления командой.',
    // Reports periods
    thisMonth: 'Этот месяц',
    lastMonth: 'Прошлый месяц',
    thisQuarter: 'Этот квартал',
    thisYear: 'Этот год',
    custom: 'Произвольный',
    dailyBreakdown: 'По дням',
    // Add transaction modal
    selectAccount: 'Выберите счёт',
    noCategory: 'Без категории',
    errValidAmount: 'Введите корректную сумму',
    errSelectAccount: 'Выберите счёт',
    errSelectDestAccount: 'Выберите счёт получателя',
    errDiffAccounts: 'Счета отправителя и получателя должны отличаться',
    errSomethingWrong: 'Что-то пошло не так',
    errNameRequired: 'Введите название',
    // Invoice form
    currency: 'Валюта',
    clientRequired: 'Укажите имя клиента',
    validAmount: 'Введите корректную сумму',
    servicesRendered: 'Оказанные услуги',
    yourCompany: 'Ваша компания',
  },

  kz: {
    // Tabs
    transactions: 'Транзакциялар',
    budget: 'Бюджет',
    analytics: 'Аналитика',
    calendar: 'Күнтізбе',
    users: 'Пайдаланушылар',
    invoices: 'Шот-фактуралар',
    taxes: 'Салықтар',
    payroll: 'Жалақы',
    taxesSubtitle: 'Салық есебі және жақын тапсыру мерзімдері',
    payrollSubtitle: 'Жалақы ұсталымдары мен қызметкердің толық құны',
    // Sidebar
    totalBalance: 'Шоттардағы жалпы сома',
    myAccounts: 'Менің шоттарым',
    signOut: 'Шығу',
    business: 'Бизнес',
    personal: 'Жеке тұлға',
    // Actions
    income: 'Кіріс',
    expense: 'Шығыс',
    transfer: 'Аударым',
    addIncome: '+ Кіріс',
    addExpense: '− Шығыс',
    addTransfer: '⇄ Аударым',
    // Transactions
    description: 'Сипаттама',
    category: 'Санат',
    account: 'Шот',
    date: 'Күні',
    amount: 'Сома',
    week: 'Апта',
    month: 'Ай',
    quarter: 'Тоқсан',
    year: 'Жыл',
    allTime: 'Барлық уақыт',
    all: 'Барлығы',
    search: 'Іздеу...',
    profit: 'Пайда',
    noTransactions: 'Транзакциялар табылмады',
    noTransactionsSub: 'Сүзгіні өзгертіп немесе транзакция қосыңыз',
    comment: 'Пікір',
    // Analytics
    cashFlow: 'Ақша ағыны',
    totalIncome: 'Жалпы кіріс',
    totalExpenses: 'Жалпы шығыс',
    netProfit: 'Таза пайда',
    incomeVsExpenses: 'Кіріс және шығыс',
    profitTrend: 'Пайда динамикасы',
    topCategories: 'Үздік шығыс санаттары',
    months3: '3 ай',
    months6: '6 ай',
    months12: '12 ай',
    // Calendar
    today: 'Бүгін',
    noData: 'Транзакциялар жоқ',
    weekDays: ['Дс', 'Сс', 'Ср', 'Бс', 'Жм', 'Сб', 'Жк'],
    // Users
    teamMembers: 'Команда мүшелері',
    inviteUser: 'Шақыру',
    owner: 'Иесі',
    admin: 'Әкімші',
    member: 'Мүше',
    inviteSent: 'Шақыру жіберілді!',
    emailPlaceholder: 'колла@компания.com',
    role: 'Рөл',
    joined: 'Қосылды',
    pendingInvite: 'Күтудегі шақыру',
    // Invoices
    createInvoice: 'Жаңа шот',
    invoiceNumber: 'Шот №',
    client: 'Клиент',
    status: 'Мәртебе',
    issueDate: 'Берілген күні',
    dueDate: 'Төлем мерзімі',
    total: 'Сома',
    paid: 'Төленді',
    pending: 'Күтудегі',
    overdue: 'Мерзімі өткен',
    draft: 'Жоба',
    allStatuses: 'Барлық мәртебелер',
    noInvoices: 'Шот-фактуралар жоқ',
    noInvoicesSub: 'Алғашқы шот-фактураны жасаңыз',
    addTitle: { income: 'Кіріс қосу', expense: 'Шығыс қосу', transfer: 'Аударым' },
    saving: 'Сақталуда...',
    from: 'Шоттан',
    to: 'Шотқа',
    optionalNote: 'Қосымша пікір',
    // Categories
    categories: 'Санаттар',
    addCategory: 'Санат қосу',
    editCategory: 'Өңдеу',
    categoryName: 'Атауы',
    categoryType: 'Түрі',
    categoryColor: 'Түсі',
    categoryIcon: 'Белгішесі',
    noCategories: 'Санаттар жоқ',
    noCategoriesSub: 'Алғашқы санатты қосыңыз',
    deleteCategory: 'Жою',
    incomeCategories: 'Кіріс',
    expenseCategories: 'Шығыс',
    bothCategories: 'Екеуі де',
    // Reports
    reports: 'Есептер',
    reportPeriod: 'Кезең',
    exportCsv: 'CSV экспорт',
    exportPdf: 'Басып шығару / PDF',
    reportSummary: 'Қорытынды',
    reportByCategory: 'Санат бойынша',
    reportIncome: 'Кіріс',
    reportExpense: 'Шығыс',
    reportProfit: 'Таза пайда',
    reportTxCount: 'Транзакциялар',
    dateFrom: 'Бастап',
    dateTo: 'Дейін',
    noReportData: 'Таңдалған кезең үшін деректер жоқ',
    // Settings
    settings: 'Параметрлер',
    profile: 'Профиль',
    displayName: 'Аты-жөні',
    emailAddress: 'Email',
    defaultCurrency: 'Негізгі валюта',
    timezone: 'Уақыт белдеуі',
    dateFormat: 'Күн форматы',
    saveSettings: 'Сақтау',
    settingsSaved: 'Параметрлер сақталды!',
    preferences: 'Параметрлер',
    // Invoice detail/print
    invoiceDetail: 'Шот-фактура',
    printInvoice: 'Басып шығару',
    invoiceTo: 'Алушы',
    invoiceFrom: 'Жіберуші',
    invoiceDesc: 'Сипаттама',
    invoiceSubtotal: 'Аралық сома',
    invoiceTotal: 'Барлығы',
    // AI Analytics
    aiAnalytics: 'AI',
    aiInsights: 'AI Инсайттар',
    aiInsightsSub: 'Транзакция тарихына негізделген',
    aiAssistant: 'AI Қаржы ассистенті',
    aiPoweredBy: 'tencent/hy3-preview негізінде',
    aiAskPlaceholder: 'Қаржыңыз туралы сұраңыз...',
    noInsights: 'Инсайт алу үшін транзакциялар қосыңыз',
    aiWelcome: 'Сәлем! Мен сіздің AI қаржы ассистентіңізмін. Қаржы туралы кез келген сұрақ қойыңыз немесе төмендегі нұсқауларды таңдаңыз.',
    // Common UI
    cancel: 'Болдырмау',
    other: 'Басқа',
    language: 'Тіл',
    dangerZone: 'Қауіпті аймақ',
    deleteAccount: 'Аккаунтты жою',
    deleteAccountDesc: 'Аккаунтыңыз бен барлық деректерді толығымен жойыңыз. Бұл іс-әрекетті кері қайтару мүмкін емес.',
    teamInfo: 'Мүшелер транзакцияларды қарап, қоса алады. Әкімшілердің командаларды басқарудан басқа толық қатынасы бар.',
    // Reports periods
    thisMonth: 'Осы ай',
    lastMonth: 'Өткен ай',
    thisQuarter: 'Осы тоқсан',
    thisYear: 'Осы жыл',
    custom: 'Еркін',
    dailyBreakdown: 'Күн бойынша',
    // Add transaction modal
    selectAccount: 'Шотты таңдаңыз',
    noCategory: 'Санатсыз',
    errValidAmount: 'Дұрыс соманы енгізіңіз',
    errSelectAccount: 'Шотты таңдаңыз',
    errSelectDestAccount: 'Алушы шотты таңдаңыз',
    errDiffAccounts: 'Жіберуші және алушы шоттары әртүрлі болуы керек',
    errSomethingWrong: 'Бірдеңе дұрыс болмады',
    errNameRequired: 'Атауын енгізіңіз',
    // Invoice form
    currency: 'Валюта',
    clientRequired: 'Клиент атын енгізіңіз',
    validAmount: 'Дұрыс соманы енгізіңіз',
    servicesRendered: 'Көрсетілген қызметтер',
    yourCompany: 'Сіздің компанияңыз',
    integrations: 'Интеграциялар',
    linkTelegramBot: 'Telegram-ботты байланыстыру',
    recurring: 'Тұрақты төлемдер',
    recurringSubtitle: 'Жазылымдар мен тұрақты шығындарды басқарыңыз',
    addRecurring: 'Төлем қосу',

    // ── Budget Widget ──
    personalBudget: 'Жеке бюджет',
    personalBudgetSubtitle: 'Жеке шығындар мен тұрақты төлемдерді жоспарлаңыз',
    budgetSubtitle: 'Жоспарланғаннан тағы қанша жұмсауға болады',
    rollover: 'Ауыстыру',
    rolloverEnabled: 'Қалдықты ауыстыру',
    rolloverDesc: 'Егер ай соңында пайдаланылмаған ақша қалса — ол келесі айдың бюджетіне қосылады',
    aiAnalyzing: 'Шығындар тарихын талдап жатырмын…',
    aiWait: 'Бұл шамамен 10 секунд алады',
    aiError: 'Бюджетті құру мүмкін болмады',
    aiBudget: 'AI-бюджет',
    planned: 'Жоспарланған',
    spent: 'Жұмсалды',
    remaining: 'Қалды',
    overrun: 'артық шығын',
    save: 'Сақтау',
    editBudget: 'Бюджетті өзгерту',
    createBudget: 'Бюджет құру',
    notePlaceholder: 'Мысалы: Magnum + Galmart',
    categoryExceeded: 'санаттан асты',
    categoriesExceeded: 'санаттардан асты',
    closeToLimit: 'лимтке жақын',
    balancedBudget: 'Бюджет теңгерілген — әрбір Теңге бөлінген.',
    toBudgetLabel: 'Бөлуге',
    exceedsIncome: 'жоспарлар кірістен асады',
    rolloverDone: 'Ауыстырылды',
    plannedLabel: 'Жоспарланған',
    spentLabel: 'Жұмсалды',
    toBudget: 'Бөлуге',
    budgetBalanced: 'Бюджет теңгерілген — әрбір Теңге бөлінген.',
    noLimit: 'лимит жоқ',
    errPositiveAmount: 'Оң соманы енгізіңіз',
    category: 'Санат',
    plannedPerMonth: 'Айға жоспарланған, ₸ *',
    note: 'Жазба',
    errCategoryName: 'Санат атауын енгізіңіз',
    errCategoryExists: 'Мұндай санат бюджетте бар',
    add: 'Қосу',
    addCategoryToBudget: '+ Санатты бюджетке қосу',
    prevMonth: 'Өткен ай',
    nextMonth: 'Келесі ай',
    assignToCategories: '— оларды санаттарға бөліңіз, сонда әрбір теңгенің өз орны болады',
    plansExceedIncome: '— жоспарлар кірістен асады; санаттардағы лимиттерді азайтыңыз',
    aiFallback: 'AI қате жауап берді — тарих бойынша орташа мән пайдаланылды.',
    aiAnalysisMonths: 'Айлар бойынша талдау',
    aiCheckboxHint: 'Қосқыңыз келмейтін санаттардан белгіні алып тастаңыз.',
    avg3Months: '3 айдағы орташа мән',
    aiApplying: 'Бюджетті қолданып жатырмын…',
    selected: 'Таңдалды',
    sum: 'Сома',
    apply: 'Қолдану',
    noBudgetsThisMonth: 'Бұл айда әзірге бюджеттер жоқ.',
    addFirstCategoryHint: 'Төменде алғашқы санатты қосыңыз.',
    deleteBudgetConfirm: 'Санат бюджетін жою',
    confirmRollover: 'Қалдықтарды ауыстыру',
    rolloverApplied: 'Ауыстыру қолданылды',
    categoriesLabel: { one: 'санат', other: 'санаттар' },
    remainingTotal: 'Барлығы қалды',
    edit: 'Өзгерту',
    delete: 'Жою',
    budgetAlertTitle: 'Бюджет',
    openBudget: 'Бюджетті ашу',
    budgetNotSet: 'Бұл санатқа осы айда бюджет орнатылмаған. Жұмсалды:',
    willExceedLimit: 'Лимиттен асады',
    remainingInCat: 'Санатта қалды:',
    afterOperation: 'операциядан кейін',
    currentlyRemaining: 'Қазір қалды:',
    fromTotalOf: 'барлығы',
    fromLabel: 'ішінен',
    errSelectAtLeastOne: 'Кем дегенде бір санатты таңдаңыз',

    // ── Goals - Business ──
    bizGoalsTitle: 'Бизнес мақсаттары',
    bizGoalsSubtitle: 'Резервтерді, міндеттемелерді және компанияның өсуіне салынатын инвестицияларды жоспарлаңыз',
    newBizGoal: 'Жаңа бизнес-мақсат',
    editBizGoal: 'Бизнес-мақсатты өңдеу',
    bizGoalNameLabel: 'Бизнес-мақсат атауы *',
    bizGoalNameError: 'Бизнес-мақсат атауын көрсетіңіз',
    bizGoalPlaceholder: 'Мысалы: 3 айлық шығынға резерв',
    bizGoalsCount: 'Бизнес мақсаттары',
    reservedLabel: 'Резервтелді',
    reservedInputLabel: 'Резервтелген сома, ₸',
    reservePlaceholder: 'Резерв сомасы, ₸',
    bizTargetLabel: 'Жоспар',
    bizCompleteCountLabel: 'Жабылды',
    bizGoalCreated: 'Бизнес-мақсат жасалды',
    bizGoalUpdated: 'Бизнес-мақсат жаңартылды',
    bizGoalDeleted: 'Бизнес-мақсат жойылды',
    bizDeleteGoalConfirm: 'Бизнес-мақсатты жою',
    bizEmptyTitle: 'Әзірге бизнес-мақсаттар жоқ',
    bizEmptySubtitle: 'Резерв, еңбекақы қоры, салықтар немесе бизнестің өсуі бойынша жоспар құрыңыз',
    needReserve: 'Резервтеу керек',
    bizGoalComplete: 'Мақсат жабылды',
    reserveAction: '+ Резервтеу',
    reserveTitle: 'Резервтеу',
    reserveToGoal: 'Мақсатқа дейін резервтеу керек',
    reservedToast: 'Резервтелді',

    // ── Goals - Personal ──
    goalsTitle: 'Қаржылық мақсаттар',
    goalsSubtitle: 'Жинақтарды, қауіпсіздік жастығын, ірі сатып алуларды және жеке басымдықтарды жоспарлаңыз',
    newGoal: 'Жаңа мақсат',
    editGoal: 'Мақсатты өңдеу',
    nameLabel: 'Атауы *',
    nameError: 'Атауын көрсетіңіз',
    namePlaceholder: 'Мысалы: Қауіпсіздік жастығы немесе демалыс',
    goalsCount: 'Қаржылық мақсаттар',
    savedLabel: 'Жиналды',
    savedInputLabel: 'Жиналған сома, ₸',
    depositPlaceholder: 'Толықтыру сомасы, ₸',
    targetLabel: 'Мақсатты сома',
    completeCountLabel: 'Қол жеткізілді',
    goalCreated: 'Мақсат жасалды',
    goalUpdated: 'Мақсат жаңартылды',
    goalDeleted: 'Мақсат жойылды',
    deleteGoalConfirm: 'Мақсатты жою',
    emptyTitle: 'Әзірге мақсаттар жоқ',
    emptySubtitle: 'Жинақтар, қауіпсіздік жастығы немесе ірі сатып алу үшін мақсат құрыңыз',
    needAccumulate: 'Жинайтын сома қалды',
    goalComplete: 'Мақсатқа қол жеткізілді',
    depositAction: '+ Толықтыру',
    depositTitle: 'Толықтыру',
    depositToGoal: 'Мақсатқа дейін жинау керек',
    depositedToast: 'Мақсатқа қосылды',

    // ── Goal common ──
    planAmountLabel: 'Жоспарлы сома, ₸ *',
    errPlanAmount: 'Жоспарлы соманы көрсетіңіз',
    deadlineLabel: 'Мақсат мерзімі (міндетті емес)',
    iconLabel: 'Белгіше',
    colorLabel: 'Түс',
    goalDaysLeft: 'күн',
    goalReached: 'Қол жеткізілді!',
    reserveLabel: 'Резерв',
    payrollLabel: 'Еңбекақы қоры',
    taxLabel: 'Салықтар',
    capitalLabel: 'Капитал',
    growthLabel: 'Өсу',
    automationLabel: 'Автоматтандыру',
    allRemaining: 'Барлық қалдық',
    monthsNames: ['Қаңтар', 'Ақпан', 'Наурыз', 'Сәуір', 'Мамыр', 'Маусым', 'Шілде', 'Тамыз', 'Қыркүйек', 'Қазан', 'Қараша', 'Желтоқсан'],
    weekDays: ['Дс', 'Сс', 'Ср', 'Бс', 'Жм', 'Сб', 'Жк'],

    // ── Analytics ──
    personalCashFlow: 'Жеке ақша ағыны',
    bizCashFlow: 'Бизнес ақша ағыны',
    planBtn: 'Жоспар',
    netLabelPersonal: 'Қалдық',
    netLabelBiz: 'Таза пайда',
    forecastPersonalTitle: '60 күндік жеке болжам',
    forecastBizTitle: '60 күндік Cash Flow болжамы',
    riskLowMoney: 'Ақша жетіспеушілігі қаупі',
    riskGap: 'Кассалық алшақтық қаупі',
    riskLowLiquidity: 'Өтімділіктің төмен қоры',
    riskNormalLiquidity: 'Өтімділік қоры қалыпты',
    forecastPersonalDesc: 'Болашақ теңгерімді ағымдағы шоттарды, тұрақты төлемдерді және қаржылық мақсаттарды ескере отырып есептейді.',
    forecastBizDesc: 'Болашақ теңгерімді ағымдағы шоттарды, күтілетін шот-фактураларды, жалақыны және бизнес-мақсаттар бойынша резервтерді ескере отырып есептейді.',
    balanceNow: 'Қазіргі теңгерім',
    incomePlan: 'Кіріс жоспары',
    expensePlan: 'Шығыс жоспары',
    minBalance: 'Мин. қалдық',
    minimum: 'Минимум',
    remTrend: 'Қалдық динамикасы',
    profitTrend: 'Пайда динамикасы',
    salaryLabel: 'Жалақы',
    planSuffix: '(жоспар)',
    totalIncome: 'Жалпы кіріс',
    totalExpenses: 'Жалпы шығыс',
    netProfit: 'Таза пайда',
    incomeVsExpenses: 'Кіріс және шығыс',
    topCategories: 'Үздік шығыс санаттары',
    months3: '3 ай',
    months6: '6 ай',
    months12: '12 ай',

    // ── Taxes ──
    taxes: 'Салықтар',
    taxesSubtitle: 'Салық есебі және жақын тапсыру мерзімдері',
    taxTypeLabel: 'Салық түрі',
    taxAmountLabel: 'Есептелген сома',
    taxDeadlineLabel: 'Төлеу мерзімі',
    taxStatusLabel: 'Мәртебе',
    taxSimplifiedIP: 'Оңайлатылған (ЖК)',
    taxSimplifiedTOO: 'Оңайлатылған (ЖШС)',
    taxGeneralIP: 'Жалпы (ЖК)',
    taxGeneralTOO: 'Жалпы (ЖШС, КТС)',
    taxForm: 'форма',
    taxChangeRegime: 'Режимді өзгерту',
    taxLoading: 'Салықтар жүктелуде...',
    taxPeriodIncome: 'Кезең үшін кіріс',
    taxPeriodExpense: 'Кезең үшін шығыс',
    taxProfit: 'Пайда',
    taxLabel: 'Салық',
    taxToday: 'Бүгін!',
    taxDaysLeft: 'күн қалды',
    taxDayLeft: 'күн қалды',
    taxAdvice: '💡 Айыппұлдарды болдырмау үшін {amount} алдын ала бөлек қойыңыз',
    taxHalf1: '1-жартыжылдық',
    taxHalf2: '2-жартыжылдық',
    taxDue: 'тапсыру мерзімі',
    taxPersonalIncome: 'ЖК (Жеке табыс салығы)',
    taxSocial: 'Әлеуметтік салық',
    taxPension: 'БЖЗҚ (Зейнетақы жарналары)',
    taxMedical: 'МӘМС (Медициналық сақтандыру)',
    taxVat: 'ҚҚС (Қосылған құн салығы)',

    // ── Payroll ──
    payroll: 'Жалақы',
    payrollSubtitle: 'Жалақы ұсталымдары мен қызметкердің толық құны',
    salaryGross: 'Қолға алатын сома (Net)',
    salaryNet: 'Есептелген жалақы (Gross)',
    payrollTaxes: 'Салықтар мен жарналар',
    totalCost: 'Қызметкердің толық құны',
    payrollAddEmp: 'Сотрудник',
    payrollNewEmp: 'Жаңа қызметкер',
    payrollEmpty: 'Есептеуді бастау үшін қызметкерлерді қосыңыз',
    payrollDetailed: 'Егжей-тегжейлі есептеу',
    payrollFromGrossShort: 'Начисл.',
    payrollFromNetShort: 'Қолға',
    payrollEmployeeDed: 'Қызметкерден ұсталымдар',
    payrollMciDed: '14 АЕК шегерімі',
    payrollIitBase: 'ЖТС базасы',
    payrollEmployerContr: 'Жұмыс беруші есебінен',
    payrollSelectEmp: 'Мәліметтерді көру үшін қызметкерді таңдаңыз',
    payrollImpact: 'Бизнеске әсері',
    payrollEmployerLoad: 'Жұмыс берушінің жүктемесі',
    payrollRaise10: 'жалақыға +10%',
    payrollNewHireHint: '300 000 окладпен жаңа қызметкер',
    payrollAddToAnalytics: 'ЖҚҚ-ны аналитикаға қосу',
    payrollAddedToast: 'Жалақы қоры аналитикаға жоспарлы шығыс ретінде қосылды',
    payrollDiscl: 'Есептеулерде {mzp}₸ ТЖМ және {mrp}₸ АЕК пайдаланылады. Нақты төлем алдында өзекті ережелерді тексеріңіз.',
    payrollReverseCalc: 'Қолға алатын сомадан окладты таңдау',
    payrollNetPlaceholder: 'Қолға, ₸',
    payrollEstGross: 'Шамамен есептеу керек',
    monthShort: 'ай',

    // ── Invoices ──
    createInvoice: 'Жаңа шот',
    invoiceNumber: 'Шот №',
    client: 'Клиент',
    status: 'Мәртебе',
    issueDate: 'Берілген күні',
    dueDate: 'Төлем мерзімі',
    total: 'Сома',
    paid: 'Төленді',
    pending: 'Күтудегі',
    overdue: 'Мерзімі өткен',
    draft: 'Жоба',
    allStatuses: 'Барлық мәртебелер',
    noInvoices: 'Шот-фактуралар жоқ',
    noInvoicesSub: 'Алғашқы шот-фактураны жасаңыз',
    invoiceTo: 'Алушы',
    invoiceFrom: 'Жіберуші',
    invoiceDesc: 'Сипаттама',
    invoiceSubtotal: 'Аралық сома',
    invoiceTotal: 'Барлығы',
    servicesRendered: 'Көрсетілген қызметтер',

    // ── Users & Team ──
    teamMembers: 'Команда мүшелері',
    inviteUser: 'Шақыру',
    owner: 'Иесі',
    admin: 'Әкімші',
    member: 'Мүше',
    inviteSent: 'Шақыру жіберілді!',
    emailPlaceholder: 'колла@компания.com',
    role: 'Рөл',
    joined: 'Қосылды',
    pendingInvite: 'Күтудегі шақыру',
    teamInfo: 'Мүшелер транзакцияларды қарап, қоса алады. Әкімшілердің командаларды басқарудан басқа толық қатынасы бар.',

    // ── Settings ──
    settings: 'Баптаулар',
    profile: 'Профиль',
    displayName: 'Аты-жөні',
    emailAddress: 'Email',
    defaultCurrency: 'Негізгі валюта',
    timezone: 'Уақыт белдеуі',
    dateFormat: 'Күн форматы',
    saveSettings: 'Сақтау',
    settingsSaved: 'Параметрлер сақталды!',
    preferences: 'Теңшелімдер',
    dangerZone: 'Қауіпті аймақ',
    deleteAccount: 'Аккаунтты жою',
    deleteAccountDesc: 'Аккаунтыңыз бен барлық деректерді толығымен жойыңыз. Бұл іс-әрекетті кері қайтару мүмкін емес.',
    profileTypeLabel: 'Профиль түрі',
    profileTypeDesc: 'Бірінші сауалнама кезінде бір рет таңдалады',
    subscription: 'Жазылым',
    plan: 'Тариф',
    statusK: 'Күйі',
    trial: 'Сынақ мерзімі',
    active: 'Белсенді',
    pastDue: 'Мерзімі өткен',
    canceled: 'Бас тартылды',
    trialEnds: 'Сынақ мерзімі аяқталады',
    nextBilling: 'Келесі төлем',
    manageSubscription: 'Жазылымды басқару',
    noActiveSubscription: 'Белсенді жазылым жоқ',
  },
}

// ─── Landing page translations ────────────────────────────────────────────────
export const landingT = {
  en: {
    menu: 'Menu',
    navLinks: [
      { label: 'Features', href: '#features' },
      { label: 'How It Works', href: '#how-it-works' },
      { label: 'Who Is It For', href: '#for-business' },
      { label: 'Pricing', href: '#pricing' },
    ],
    signUp: 'Try It Now',
    myAccount: 'My Account',
    heroTag: '✦ Smart Finance for Kazakhstan',
    heroTitle: "Take Full Control of Your Finances",
    heroTitleLine1: "Take Full Control",
    heroTitleLine2: "of Your Finances",
    heroSub: 'Gain full control: AI analytics transforms your entries into accurate forecasts and offers management advice. Visual charts, a payment calendar, and deep personalization — see the full financial picture and plan your future with confidence.',
    heroTrust1: '11 KZ banks supported',
    heroTrust2: 'Bank-grade encryption',
    heroTrust3: '3-min setup',
    tryFree: 'Try It Now',
    freeBadge: 'Quick start',
    freeDemo: 'See how it works',
    demoBadge: '2 min',
    googleRating: 'Google Rating',
    trialNote: 'Start with manual entry or a bank statement upload',
    forecastSubtitle: 'Financial Forecast',
    analyticsSubtitle: '24/7 Analytics',
    reportsSubtitle: 'PDF Reports',
    featTitle: 'Finvy — Financial Peace of Mind for Your Business',
    featSub: 'Ditch spreadsheets and guesswork — get full control of your finances with a simple online tool. Track your cash flow, plan payments, and keep your profit on track',
    aiCopTitle: 'AI Copilot Finvy',
    aiCopNew: 'New',
    aiCopSub: 'Your personal AI assistant for personal and business finance',
    aiMonthly: 'Monthly Reports',
    aiMonthlyDesc: 'Get a monthly PDF report with detailed income and expense analysis',
    aiInsights: 'Financial Insights',
    aiInsightsDesc: 'AI-powered analysis of your spending patterns and forecasts',
    aiAlerts: 'Smart Alerts',
    aiAlertsDesc: 'Proactive notifications before cash flow gaps occur',
    withoutApp: 'Without Finvy',
    withApp: 'With Finvy',
    integrationsCount: '',
    integrationsSub: '',
    integrationsAlso: 'Also',
    integrationsApiDesc: 'Includes a custom API for seamless integration tailored to your needs',
    featAnalTag: 'Analytics',
    featAnalTitle: 'Flexible Financial Management',
    featAnalDesc: "Forget about financial chaos. Customize income and expense categories, manage cash flow, and always know what's working and what's draining your resources.",
    featCalTag: 'Calendar',
    featCalTitle: 'Manage Payments and Receipts',
    featCalDesc: "Money doesn't disappear — it either works for you, or you lose it. Finvy helps you keep your financial balance under control.",
    problems: [
      { icon: '📊', title: 'You manage finances in spreadsheets', desc: 'Calculations in tables take time and increase the risk of errors' },
      { icon: '👁', title: 'Checks, debts, and notes — everything can get overlooked', desc: 'Important payments might slip through the cracks' },
      { icon: '📈', title: 'There is an accountant, but no full control', desc: 'You only learn about project profitability or cash flow gaps after the fact' },
      { icon: '👥', title: 'The team is not involved in financial management', desc: 'Important payments may go unnoticed' },
      { icon: '💰', title: 'Cash flow gaps are affecting businesses', desc: 'There is no money even for critical expenses because there was no forecast' },
    ],
    solutions: [
      { icon: '🧮', title: 'Simple analytics for projects, clients, and employees — everything is clear at a glance' },
      { icon: '📁', title: 'No missed receipts or outstanding debts', desc: 'Every transaction is under control, in one unified system' },
      { icon: '🔄', title: 'Financial data is always up-to-date, 24/7', desc: 'Automatic bank uploads and real-time synchronization across devices' },
      { icon: '💰', title: 'Manage personal and business finances together', desc: 'One system for full control over all income and expenses' },
      { icon: '🔔', title: 'Proactive cash gap alerts', desc: 'Finvy predicts cash flow and alerts you to potential risks in advance' },
    ],
    howTitle: 'How Does it Work?',
    howSub: 'No matter your business type — if you have income and expenses, Finvy helps you track and manage them effortlessly',
    stepLabel: 'Step',
    steps: [
      { title: 'Add income and expenses manually or by voice', desc: 'Quick transaction entry via the interface, Telegram bot, or voice message — choose the most convenient way.' },
      { title: 'All transactions in one place — in real time', desc: 'Income and expenses collected in one unified system. Always see your current financial status.' },
      { title: 'Full control: cash flow, P&L, and balance sheet', desc: 'See the complete financial picture of your business: where money comes from and where it goes.' },
      { title: 'Your data is secure', desc: 'All financial data is encrypted and stored on secure servers. Only you have access.' },
      { title: 'Ongoing support and expert consultation', desc: 'Need help? Our team is always ready to assist you in setting up Finvy for your business.' },
      { title: 'AI assistant analyzes your finances', desc: 'Get personalized recommendations, forecasts and insights thanks to artificial intelligence.' },
    ],
    liveTitle: 'Do you want to see everything live?',
    liveSub: "We will help you set up your first workspace",
    liveBtn: 'See Finvy in Action',
    liveBtnBadge: 'START',
    stats: [
      { value: '54', label: 'Countries where businesses manage finances with Finvy', icon: '🌐' },
      { value: '94%', label: 'Clients recommend us to colleagues and partners', icon: '💬' },
      { value: '100+', label: 'Business sectors', icon: '🔵' },
    ],
    trustedTitle: 'Trusted by Growing Businesses Worldwide',
    trustedSub: 'Join the companies that manage their finances with Finvy',
    supportTitle: "We're Here to Support You — Every Step of the Way",
    supportMobile: 'Mobile App',
    supportMobileSub: 'iOS & Android available',
    supportChat: '24/7 Chat Support',
    supportChatSub: 'Available via Telegram & WhatsApp',
    supportConsult: 'Expert Consultations',
    supportConsultSub: 'Personal onboarding sessions',
    bizTitle: 'Take Control of Your Finances — See Profit Tomorrow',
    bizSub: 'Manage manually or by voice. Enter expenses anytime,\nFinvy categorizes and shows you the real picture — always up-to-date, 24/7',
    businesses: ['IT & Software', 'E-commerce', 'Retail', 'Services', 'Construction', 'Healthcare', 'Hospitality', 'Education', 'Manufacturing', 'Logistics', 'Marketing', 'Real Estate'],
    bizCTA: 'Cash Flow + P&L ready\nin 3 minutes, not 3 days',
    bizBtn: 'Try It Now',
    bizFeatures: [['Cash Flow', 'ready immediately'], ['P&L', 'by categories'], ['PDF', 'for reporting']],
    bizChartYear: 'For the current year',
    bizChartCat: 'By categories ▾',
    bizChartLines: 'Transfer lines ▾',
    vs1cBadge: 'Comparison',
    vs1cTitle: 'Finvy vs',
    vs1cSub: '1С is designed for accountants and tax authorities. Finvy is for business owners who need to manage money here and now.',
    vs1cParam: 'Parameter',
    vs1cFinvy: 'Finvy',
    vs1cRows: [
      { aspect: 'Price', Finvy: 'From $0 — free plan available', onec: 'From ₽40,000 + setup + support' },
      { aspect: 'Setup time', Finvy: 'Ready in 5 minutes — register and go', onec: 'Weeks of installation, setup, and training' },
      { aspect: 'Access', Finvy: 'Browser, phone, tablet — anywhere', onec: 'Tied to a specific PC / server' },
      { aspect: 'Updates', Finvy: 'Automatic, no action required', onec: 'Paid, requires IT specialist' },
      { aspect: 'Focus', Finvy: 'Management accounting: cash, profit, gaps', onec: 'Bookkeeping and taxes — not for operations' },
      { aspect: 'Analytics speed', Finvy: 'Full picture in 30 seconds', onec: 'Reports take hours, require an accountant' },
      { aspect: 'Teamwork', Finvy: 'Role-based access, real-time collaboration', onec: 'One workstation or expensive network version' },
      { aspect: 'AI assistant', Finvy: 'Built-in — analyzes data and gives advice', onec: 'Not available' },
      { aspect: 'Needs IT / accountant', Finvy: 'No — any employee can handle it', onec: 'Yes — cannot do without a specialist' },
    ],
    vs1cSwitchCTA: 'Switch to Finvy in 5 minutes',
    vs1cSwitchSub: 'No installation, IT specialists, or complex configuration',
    vs1cBtn: 'Try It Now →',
    pricingTitle: 'Current tariffs',
    pricingSub: 'Choose a plan that fits your business.\nStart with manual entry or a bank statement upload',
    monthly: 'Monthly',
    halfYear: 'Half a year',
    annually: 'Annually',
    mostPopular: 'Most Popular',
    perMonth: '/ month',
    firstFree: 'Start now',
    pricingCustom: 'Custom',
    pricingFree: 'Free',
    additionalTitle: 'Boost Your Efficiency\nwith Additional Services',
    additionalServices: [
      { icon: '🏦', title: 'Bank integration*', price: '$3 / month', note: '* Connect your bank account for automatic transaction import. Transactions, balances, and account data are synced in real time via Open Banking API.' },
      { icon: '🔗', title: 'Import from 1C, Excel, CSV, PDF', price: '$3 / month', note: 'Transfer your financial data from 1C, Excel, Google Sheets, or bank statements (CSV/PDF) into Finvy in a few clicks.' },
      { icon: '📊', title: 'Cash Flow Forecast report', price: '$5 / month', note: 'AI-powered prediction of your cash flow for the next 30/60/90 days based on transaction history.' },
    ],
    plans: [
      { name: 'Starter', monthly: 10, half: 9, annual: 8, cta: 'Start now', desc: 'For individuals getting started', features: ['4 users', 'Cash Flow report', 'Telegram bot', 'AI only support'] },
      { name: 'Business', monthly: 20, half: 17, annual: 16, cta: 'Start now', desc: 'For small teams', highlight: true, features: ['6 users', 'Unlimited Cash Flow + P&L', 'Telegram bot', 'AI + support chat'] },
      { name: 'Corporate', monthly: null, half: null, annual: null, cta: 'Contact Sales', desc: 'For enterprises', features: ['Unlimited users', 'All reports + Advanced analytics', 'Priority support', 'Dedicated manager', 'Custom integrations'] },
    ],
    reviewsTitle: 'What Our Clients Say',
    reviews: [
      { name: 'Alexander M.', company: 'IT Company, 15 employees', text: 'Finally found a tool that actually works for our business. We see all cash flows in real time and stopped losing money on unnoticed expenses.', rating: 5 },
      { name: 'Maria K.', company: 'Online Store', text: 'Set up in one evening. Now I always know where my money is going. The automatic bank sync alone saves me hours every week.', rating: 5 },
      { name: 'Denis R.', company: 'Construction Business', text: 'We have 12 projects running simultaneously. Finvy helps us track profitability of each one. The team has been incredibly helpful.', rating: 5 },
      { name: 'Olga T.', company: 'Marketing Agency', text: 'Migrated from spreadsheets after years. The learning curve was minimal and the time savings are huge. Highly recommend to any business owner.', rating: 5 },
    ],
    readyTitle: 'Ready to Take Control of Your Finances?',
    bookDemo: 'Start setup',
    trialNote2: 'Create a workspace and add your first real data',
    footerDesc: 'Cash flow management software for business. Take control of your finances today.',
    footerLinkTitles: { Product: 'Product', Company: 'Company', Support: 'Support', Legal: 'Legal' },
    footerLinks: {
      Product: ['Features', 'Pricing', 'How It Works', 'Integrations', 'Security', 'API'],
      Company: ['About Us', 'Blog', 'Careers', 'Press', 'Partners'],
      Support: ['Help Center', 'Contact Us', 'Status', 'Community', 'Changelog'],
      Legal: ['Privacy Policy', 'Terms of Service', 'Cookie Policy', 'GDPR'],
    },
    copyright: '© 2025 Finvy. All rights reserved.',

    appDemoTitle: 'How It Works',
    appDemoSub: 'All your accounts and transactions — in one place',
    appDemoBusiness: 'Business',
    appDemoIncome: '+ Income',
    appDemoExpense: '− Expense',
    appDemoTransfer: '⇄ Transfer',
    appDemoTotal: 'Total amount on accounts',
    appDemoMyAccounts: 'My accounts',
    appDemoTabs: ['Transactions', 'Analytics', 'Calendar', 'Users', 'Invoices', 'Auto rules'],
    appDemoHeaders: ['Date', 'Amount', 'Account/balance', 'Counterparty', 'Category', 'Comment'],
    appDemoAllTime: 'All time',
    appDemoSearch: 'Search by accounts, customers, comments',
    appDemoSum: 'Sum',
    appDemoFrom: 'From',
    appDemoTo: 'To',
    appDemoFilter: 'Filter',
    appDemoFutureTx: 'Future transactions • 95',
    appDemoSet: 'Set',
    appDemoAccBank: 'Bank card',
    appDemoAccCash: 'Cash',
    appDemoAccDebit: 'Debit card',
    appDemoAccReserve: 'Reserve fund',
    appDemoCatMusic: 'Music & events',
    appDemoCatEquip: 'Equipment sale',
    appDemoCatOther: 'Other expenses',
    appDemoCmtSocial: 'Social support',
    appDemoCatSales: 'Sales',
    appDemoCatSalary: 'Salary',
    appDemoCatServices: 'Services',
    appDemoCatComm: 'Telecom',
    appDemoCatRent: 'Rent',
    appDemoCmtRent: 'March 2026',

    heroAiActive: 'Active',
    heroAiFound: 'Found {amount} of unused cashback',
    heroAiTip: 'Kaspi Business → transfer payroll to Freedom Bank',
    heroAiApply: 'Apply optimization',

    cashbackSectionTag: '✦ New Feature',
    cashbackSectionTitle: "Find out how much you lose on the wrong cashback",
    cashbackSectionSub: 'No app in Kazakhstan compares cashback across all banks at once. Finvy shows which card to use at each store — and saves you up to',
    cashbackSectionSubHighlight: '15 000 ₸/month',
    cashbackSectionSubEnd: 'Upload your statement and see your potential savings.',
    cashbackStats: [
      { value: '11', label: 'Banks analyzed', sub: '20 cards in the database' },
      { value: '37%', label: 'Max cashback', sub: 'On partner purchases' },
      { value: '144K ₸', label: 'Average annual gain', sub: 'Based on typical spending' },
      { value: '3 min', label: 'Report generation', sub: 'Select period → get recommendation' },
    ],
    cashbackExampleTitle: 'Example: your spending for the month',
    cashbackExampleRows: [
      { cat: '🛒 Groceries', spend: '80 000 ₸', best: 'HomeCard Lite', pct: '10%', earn: '8 000 ₸' },
      { cat: '⛽ Fuel', spend: '30 000 ₸', best: 'HomeCard Lite', pct: '10%', earn: '3 000 ₸' },
      { cat: '🍽 Restaurants', spend: '25 000 ₸', best: 'Bereke ALL IN Premium', pct: '8%', earn: '2 000 ₸' },
      { cat: '🚕 Taxi', spend: '15 000 ₸', best: 'Bereke ALL IN Premium', pct: '15%', earn: '2 250 ₸' },
    ],
    cashbackExampleTotal: 'Monthly cashback',
    cashbackExampleYear: 'Per year',
    cashbackSteps: [
      { icon: '📊', title: 'Add transactions', desc: 'The system sees your real spending by category — groceries, taxi, fuel, restaurants, etc.' },
      { icon: '🏦', title: 'We compare with 11 banks', desc: 'The engine analyzes cashback programs from all banks and calculates your exact benefit' },
      { icon: '💳', title: 'Get a personalized report', desc: 'See the TOP cards with real numbers: how much ₸ comes back to you per month and per year' },
    ],
    cashbackBanksLabel: 'Banks in the analysis database',
    cashbackTableHeaders: ['Category', 'Spend', 'Best card', 'Cashback'],
    cashbackCta: 'Check my cashback →',
    cashbackCtaSub: 'Works from your real transactions',

    // ── RegisterModal ──
    regTitle: 'Try Finvy',
    bizBadge: 'Financial reports without manual collection',
    bizDesc: 'Finvy collects transactions, categories, and money movement into a clear management report for the owner.',
    bizFeatures: [['Cash Flow', 'ready immediately'], ['P&L', 'by categories'], ['PDF', 'for reporting']],
    bizProfit: 'Profit',
    bizReport: 'Report',
    regLoginTitle: 'Welcome back',
    regAlready: 'Already have an account?',
    regNoAccount: "Don't have an account?",
    regLogIn: 'Log in',
    regSignUp: 'Sign up',
    regEmail: 'Your email',
    regPassword: 'Come up with a password',
    regPhone: 'Your phone number',
    regContinue: 'Continue',
    regCreating: 'Creating account…',
    regLoggingIn: 'Logging in…',
    regOr: 'or',
    regErrEmail: 'Enter a valid email',
    regErrPassword: 'At least 6 characters',
    regErrPhone: 'Enter your phone number',
    regSetupTitle: 'Help us set up',
    regSetupTitleEnd: 'for your business',
    regCompany: 'Company name',
    regIndustry: 'Select your industry',
    regIndustries: ['IT & Software', 'E-commerce', 'Retail', 'Services', 'Construction', 'Healthcare', 'Other'],
    regTeamSize: 'Team size',
    regSizes: ['1 (just me)', '2–5', '6–20', '21–50', '51+'],
    regStartTrial: 'Get Started',
    regDoneTitle: "You're all set!",
    regDoneSub: 'Your account is ready.',
    regDoneSub2: 'Your accounts are ready to go.',
    regGoDashboard: 'Go to Dashboard →',
    regBenefits: [
      'You control expenses and avoid cash gaps',
      'You know what generates profit and what eats up the budget',
      'You plan payments in advance and sleep more peacefully',
      'You make decisions based on real numbers, not gut feeling',
      'You work comfortably on your own or with a team (accountant)',
    ],
    regLeftTitle: 'business funds easily',
    regLeftSub: '😊 you actually can manage all your',
    regStudentQ: 'Are you a student?',
    regYes: 'Yes',
    regNo: 'No',
    regRevenueQ: 'Approximate monthly revenue',
    regRevenues: ['up to 500K ₸', '500K – 2M ₸', '2 – 10M ₸', '10 – 50M ₸', '50M+ ₸'],
    regBanksQ: 'Which banks do you use?',
    regExpensesQ: 'Main expense categories',
    regExpenseTypes: ['Salary', 'Rent', 'Advertising', 'Goods procurement', 'Logistics', 'Telecom/IT', 'Taxes', 'Other'],
  },

  ru: {
    menu: 'Меню',
    navLinks: [
      { label: 'Возможности', href: '#features' },
      { label: 'Как работает', href: '#how-it-works' },
      { label: 'Кому подходит', href: '#for-business' },
      { label: 'Тарифы', href: '#pricing' },
    ],
    signUp: 'Попробовать',
    myAccount: 'Мой аккаунт',
    heroTag: '✦ Умные финансы для Казахстана',
    heroTitle: 'Возьмите финансы полностью под свой контроль',
    heroTitleLine1: 'Возьмите финансы',
    heroTitleLine2: 'полностью под свой контроль',
    heroSub: 'Обретите полный контроль: AI-аналитика превратит ваши записи в точные прогнозы и даст совет по управлению. Наглядные графики, календарь платежей и персонализация — увидьте финансовую картину целиком и планируйте будущее уверенно.',
    heroTrust1: '11 банков КЗ',
    heroTrust2: 'Банковское шифрование',
    heroTrust3: 'Настройка за 3 мин',
    tryFree: 'Попробовать сейчас',
    freeBadge: 'Быстрый старт',
    freeDemo: 'Посмотреть как работает',
    demoBadge: '2 мин',
    googleRating: 'Рейтинг Google',
    trialNote: 'Начните с ручного ввода или загрузки банковской выписки',
    forecastSubtitle: 'Финансовый прогноз',
    analyticsSubtitle: '24/7 аналитика',
    reportsSubtitle: 'PDF отчёты',
    featTitle: 'Finvy — финансовый покой для ваших личных и деловых финансов',
    featSub: 'Забудьте о таблицах и догадках — получите полный контроль над финансами с помощью простого онлайн-инструмента. Отслеживайте денежный поток и всегда знайте, куда идут деньги',
    aiCopTitle: 'AI-ассистент Finvy',
    aiCopNew: 'Новое',
    aiCopSub: 'Ваш личный AI-ассистент для личных и бизнес-финансов',
    aiMonthly: 'Ежемесячные отчёты',
    aiMonthlyDesc: 'Получайте ежемесячный PDF-отчёт с детальным анализом доходов и расходов',
    aiInsights: 'Финансовые инсайты',
    aiInsightsDesc: 'AI-анализ ваших расходов и прогнозов на основе реальных данных',
    aiAlerts: 'Умные уведомления',
    aiAlertsDesc: 'Проактивные уведомления до возникновения кассовых разрывов',
    withoutApp: 'Без Finvy',
    withApp: 'С Finvy',
    integrationsCount: '',
    integrationsSub: '',
    integrationsAlso: 'Также',
    integrationsApiDesc: 'Включает собственный API для бесшовной интеграции под ваши задачи',
    featAnalTag: 'Аналитика',
    featAnalTitle: 'Гибкое управление финансами',
    featAnalDesc: 'Забудьте о финансовом хаосе. Настраивайте категории доходов и расходов, управляйте денежным потоком и всегда знайте, что работает, а что съедает бюджет.',
    featCalTag: 'Календарь',
    featCalTitle: 'Управляйте платежами и поступлениями',
    featCalDesc: 'Деньги не исчезают — они либо работают на вас, либо вы их теряете. Finvy помогает держать финансовый баланс под контролем.',
    problems: [
      { icon: '📊', title: 'Финансы ведёте в таблицах', desc: 'Расчёты в Excel занимают время и увеличивают риск ошибок' },
      { icon: '👁', title: 'Чеки, долги и записки — что-то упускается', desc: 'Важные платежи могут ускользать из поля зрения' },
      { icon: '📈', title: 'Есть бухгалтер, но нет полного контроля', desc: 'О прибыльности проектов и кассовых разрывах узнаёте постфактум' },
      { icon: '👥', title: 'Команда не вовлечена в управление финансами', desc: 'Важные платежи могут оставаться незамеченными' },
      { icon: '💰', title: 'Кассовые разрывы бьют по бизнесу', desc: 'Денег нет даже на критические расходы, потому что не было прогноза' },
    ],
    solutions: [
      { icon: '🧮', title: 'Простая аналитика по проектам, клиентам, источникам доходов — всё видно с первого взгляда' },
      { icon: '📁', title: 'Никаких пропущенных чеков и задолженностей', desc: 'Каждая транзакция под контролем в единой системе' },
      { icon: '🔄', title: 'Финансовые данные всегда актуальны, 24/7', desc: 'Автоматическая загрузка из банков и синхронизация в реальном времени' },
      { icon: '💰', title: 'Управляйте личными и деловыми финансами вместе', desc: 'Единая система для полного контроля над всеми доходами и расходами' },
      { icon: '🔔', title: 'Проактивные уведомления о кассовых разрывах', desc: 'Finvy прогнозирует денежный поток и предупреждает о рисках заранее' },
    ],
    howTitle: 'Как это работает?',
    howSub: 'Неважно, какой у вас бизнес или как вы управляете личными финансами — если есть доходы и расходы, Finvy поможет отслеживать и управлять ими',
    stepLabel: 'Шаг',
    steps: [
      { title: 'Добавляйте доходы и расходы вручную или голосом', desc: 'Быстрый ввод транзакций через интерфейс, Telegram-бот или голосовое сообщение — выбирайте удобный способ.' },
      { title: 'Все транзакции в одном месте — в реальном времени', desc: 'Доходы и расходы собираются в единую систему. Всегда видите актуальное состояние финансов.' },
      { title: 'Полный контроль: денежный поток, P&L и баланс', desc: 'Видите полную финансовую картину бизнеса и личных финансов: откуда приходят деньги и куда уходят.' },
      { title: 'Ваши данные в безопасности', desc: 'Все финансовые данные зашифрованы и хранятся на защищённых серверах. Доступ только у вас.' },
      { title: 'Постоянная поддержка и экспертные консультации', desc: 'Нужна помощь? Наша команда всегда готова помочь настроить Finvy под ваши личные и деловые финансы.' },
      { title: 'AI-ассистент анализирует ваши финансы', desc: 'Получайте персональные рекомендации, прогнозы и инсайты благодаря искусственному интеллекту.' },
    ],
    liveTitle: 'Хотите увидеть всё вживую?',
    liveSub: 'Поможем настроить первый рабочий кабинет',
    liveBtn: 'Смотреть Finvy в действии',
    liveBtnBadge: 'СТАРТ',
    stats: [
      { value: '54', label: 'Стран, где бизнесы управляют финансами с Finvy', icon: '🌐' },
      { value: '94%', label: 'Клиентов рекомендуют нас коллегам и партнёрам', icon: '💬' },
      { value: '100+', label: 'Бизнес-секторов', icon: '🔵' },
    ],
    trustedTitle: 'Нам доверяют растущие компании по всему миру',
    trustedSub: 'Присоединяйтесь к компаниям, которые управляют финансами с Finvy',
    supportTitle: 'Мы поддержим вас на каждом шагу',
    supportMobile: 'Мобильное приложение',
    supportMobileSub: 'iOS и Android',
    supportChat: 'Чат 24/7',
    supportChatSub: 'Telegram и WhatsApp',
    supportConsult: 'Экспертные консультации',
    supportConsultSub: 'Персональный онбординг',
    bizTitle: 'Возьмите финансы под контроль — увидите прибыль завтра',
    bizSub: 'Управляйте вручную или голосом. Вводите расходы когда угодно,\nFinvy категоризирует и показывает реальную картину — всегда актуально, 24/7',
    businesses: ['IT и разработка', 'E-commerce', 'Ретейл', 'Услуги', 'Строительство', 'Медицина', 'HoReCa', 'Образование', 'Производство', 'Логистика', 'Маркетинг', 'Недвижимость'],
    bizCTA: 'Cash Flow + P&L готовы\nза 3 минуты, не за 3 дня',
    bizBtn: 'Попробовать сейчас',
    bizFeatures: [['Cash Flow', 'готов сразу'], ['P&L', 'по категориям'], ['PDF', 'для отчетности']],
    bizChartYear: 'За текущий год',
    bizChartCat: 'По категориям ▾',
    bizChartLines: 'Переводы ▾',
    vs1cBadge: 'Сравнение',
    vs1cTitle: 'Finvy vs',
    vs1cSub: '1С создана для бухгалтеров и налоговой. Finvy — для собственников, которым нужно управлять деньгами здесь и сейчас.',
    vs1cParam: 'Параметр',
    vs1cFinvy: 'Finvy',
    vs1cRows: [
      { aspect: 'Цена', Finvy: 'От 0 ₸ — есть бесплатный план', onec: 'От 40 000 ₽ + внедрение + поддержка' },
      { aspect: 'Старт работы', Finvy: 'Готово за 5 минут — регистрация и погнали', onec: 'Недели на установку, настройку и обучение' },
      { aspect: 'Доступ', Finvy: 'Браузер, телефон, планшет — везде', onec: 'Привязан к конкретному ПК / серверу' },
      { aspect: 'Обновления', Finvy: 'Автоматически, без вашего участия', onec: 'Платно, требует IT-специалиста' },
      { aspect: 'Фокус', Finvy: 'Управленческий учёт: деньги, прибыль, кассовые разрывы', onec: 'Бухгалтерия и налоги — не для операционных решений' },
      { aspect: 'Скорость аналитики', Finvy: 'Полная картина за 30 секунд', onec: 'Отчёты формируются часами, требуют бухгалтера' },
      { aspect: 'Командная работа', Finvy: 'Ролевой доступ, всё в реальном времени', onec: 'Одно рабочее место или дорогой сетевой вариант' },
      { aspect: 'AI-ассистент', Finvy: 'Встроен — анализирует данные и даёт советы', onec: 'Отсутствует' },
      { aspect: 'Нужен IT / бухгалтер', Finvy: 'Нет — справится любой сотрудник', onec: 'Да — без специалиста не обойтись' },
    ],
    vs1cSwitchCTA: 'Переходите на Finvy за 5 минут',
    vs1cSwitchSub: 'Никаких установок, IT-специалистов и сложных настроек',
    vs1cBtn: 'Попробовать сейчас →',
    pricingTitle: 'Текущие тарифы',
    pricingSub: 'Выберите подходящий план.\nНачните с ручного ввода или загрузки банковской выписки',
    monthly: 'Ежемесячно',
    halfYear: 'Полгода',
    annually: 'Ежегодно',
    mostPopular: 'Популярный',
    perMonth: '/ мес',
    firstFree: 'Начать работу',
    pricingCustom: 'Договорная',
    pricingFree: 'Бесплатно',
    additionalTitle: 'Увеличьте эффективность\nс дополнительными сервисами',
    additionalServices: [
      { icon: '🏦', title: 'Интеграция с банком*', price: '1 500 ₸ / мес', note: '* Подключите банковский счёт для автоматического импорта транзакций. Операции, балансы и данные счёта синхронизируются в реальном времени через Open Banking API.' },
      { icon: '🔗', title: 'Импорт из 1С, Excel, CSV, PDF', price: '1 500 ₸ / мес', note: 'Перенесите финансовые данные из 1С, Excel, Google Sheets или банковских выписок (CSV/PDF) в Finvy за пару кликов.' },
      { icon: '📊', title: 'Прогноз Cash Flow', price: '2 500 ₸ / мес', note: 'AI-прогноз денежного потока на 30/60/90 дней вперёд на основе истории транзакций.' },
    ],
    plans: [
      { name: 'Starter', monthly: 4500, half: 3800, annual: 3500, cta: 'Начать работу', desc: 'Для начинающих', features: ['4 пользователя', 'Отчёт Cash Flow', 'Telegram-бот', 'Только AI-поддержка'] },
      { name: 'Business', monthly: 9000, half: 7500, annual: 7000, cta: 'Начать работу', desc: 'Для небольших команд', highlight: true, features: ['6 пользователей', 'Cash Flow + P&L без ограничений', 'Telegram-бот', 'AI + чат поддержки'] },
      { name: 'Корпоративный', monthly: null, half: null, annual: null, cta: 'Связаться', desc: 'Для крупного бизнеса', features: ['Безлимит пользователей', 'Все отчёты + продвинутая аналитика', 'Приоритетная поддержка', 'Персональный менеджер', 'Индивидуальные интеграции'] },
    ],
    reviewsTitle: 'Что говорят наши клиенты',
    reviews: [
      { name: 'Александр М.', company: 'IT-компания, 15 человек', text: 'Наконец нашёл инструмент, который реально работает. Видим все денежные потоки в реальном времени — перестали терять деньги на незамеченных расходах.', rating: 5 },
      { name: 'Мария К.', company: 'Интернет-магазин', text: 'Настроила за один вечер. Теперь всегда знаю, куда идут деньги. Только автоматическая синхронизация с банком экономит несколько часов в неделю.', rating: 5 },
      { name: 'Денис Р.', company: 'Строительный бизнес', text: 'Одновременно ведём 12 проектов. Finvy помогает отслеживать прибыльность каждого. Команда поддержки — отличная.', rating: 5 },
      { name: 'Ольга Т.', company: 'Маркетинговое агентство', text: 'Перешли с таблиц после нескольких лет. Порог входа минимальный, а экономия времени — огромная. Рекомендую любому предпринимателю.', rating: 5 },
    ],
    readyTitle: 'Готовы взять финансы под контроль?',
    bookDemo: 'Начать настройку',
    trialNote2: 'Создайте кабинет и добавьте первые реальные данные',
    footerDesc: 'Программа управления денежным потоком для бизнеса. Возьмите финансы под контроль уже сегодня.',
    footerLinkTitles: { Product: 'Продукт', Company: 'Компания', Support: 'Поддержка', Legal: 'Правовая' },
    footerLinks: {
      Product: ['Возможности', 'Тарифы', 'Как работает', 'Интеграции', 'Безопасность', 'API'],
      Company: ['О нас', 'Блог', 'Вакансии', 'Пресса', 'Партнёры'],
      Support: ['Справочный центр', 'Контакты', 'Статус', 'Сообщество', 'Обновления'],
      Legal: ['Политика конфиденциальности', 'Условия использования', 'Cookie', 'GDPR'],
    },
    copyright: '© 2025 Finvy. Все права защищены.',

    appDemoTitle: 'Как это работает',
    appDemoSub: 'Все ваши счета и транзакции — в одном месте',
    appDemoBusiness: 'Бизнес',
    appDemoIncome: '+ Доход',
    appDemoExpense: '− Расход',
    appDemoTransfer: '⇄ Перевод',
    appDemoTotal: 'Общая сумма на счетах',
    appDemoMyAccounts: 'Мои счета',
    appDemoTabs: ['Транзакции', 'Аналитика', 'Календарь', 'Пользователи', 'Счета', 'Автоправила'],
    appDemoHeaders: ['Дата', 'Сумма', 'Счёт/баланс', 'Контрагент', 'Категория', 'Комментарий'],
    appDemoAllTime: 'Всё время',
    appDemoSearch: 'Поиск по счетам, контрагентам, комментариям',
    appDemoSum: 'Сумма',
    appDemoFrom: 'От',
    appDemoTo: 'До',
    appDemoFilter: 'Фильтр',
    appDemoFutureTx: 'Предстоящие транзакции • 95',
    appDemoSet: 'Задать',
    appDemoAccBank: 'Банковская карта',
    appDemoAccCash: 'Наличные',
    appDemoAccDebit: 'Дебетовая карта',
    appDemoAccReserve: 'Резервный фонд',
    appDemoCatMusic: 'Музыка и мероприятия',
    appDemoCatEquip: 'Продажа оборудования',
    appDemoCatOther: 'Прочие расходы',
    appDemoCmtSocial: 'Социальная поддержка',
    appDemoCatSales: 'Продажи',
    appDemoCatSalary: 'Зарплата',
    appDemoCatServices: 'Услуги',
    appDemoCatComm: 'Связь',
    appDemoCatRent: 'Аренда',
    appDemoCmtRent: 'Март 2026',

    heroAiActive: 'Активно',
    heroAiFound: 'Найдено {amount} неиспользованного кэшбэка',
    heroAiTip: 'Kaspi Business → переведите ФОТ на Freedom Bank',
    heroAiApply: 'Применить оптимизацию',

    cashbackSectionTag: '✦ Новая функция',
    cashbackSectionTitle: 'Узнайте, сколько вы теряете на неправильном кэшбеке',
    cashbackSectionSub: 'Ни одно приложение в КЗ не сравнивает кэшбек по всем банкам одновременно. Finvy покажет, какой картой платить в каждом магазине — и сэкономит до',
    cashbackSectionSubHighlight: '15 000 ₸/мес',
    cashbackSectionSubEnd: 'Загрузите выписку и посмотрите вашу потенциальную экономию.',
    cashbackStats: [
      { value: '11', label: 'Банков в базе', sub: '20 карт с кэшбэком' },
      { value: '37%', label: 'Макс. кэшбэк', sub: 'У партнёров банков' },
      { value: '144K ₸', label: 'Средняя выгода в год', sub: 'На типичных расходах' },
      { value: '3 мин', label: 'Генерация отчёта', sub: 'Выбери период → получи рекомендацию' },
    ],
    cashbackExampleTitle: 'Пример: ваши расходы за месяц',
    cashbackExampleRows: [
      { cat: '🛒 Продукты', spend: '80 000 ₸', best: 'HomeCard Lite', pct: '10%', earn: '8 000 ₸' },
      { cat: '⛽ Топливо', spend: '30 000 ₸', best: 'HomeCard Lite', pct: '10%', earn: '3 000 ₸' },
      { cat: '🍽 Рестораны', spend: '25 000 ₸', best: 'Береке ALL IN Premium', pct: '8%', earn: '2 000 ₸' },
      { cat: '🚕 Такси', spend: '15 000 ₸', best: 'Береке ALL IN Premium', pct: '15%', earn: '2 250 ₸' },
    ],
    cashbackExampleTotal: 'Кэшбэк в месяц',
    cashbackExampleYear: 'В год',
    cashbackSteps: [
      { icon: '📊', title: 'Добавляем транзакции', desc: 'Система видит ваши реальные траты по категориям — продукты, такси, АЗС, рестораны и т.д.' },
      { icon: '🏦', title: 'Сравниваем с 11 банками', desc: 'Движок анализирует кэшбэк-программы всех банков и считает точную выгоду на ваших расходах' },
      { icon: '💳', title: 'Получаете персональный отчёт', desc: 'Видите ТОП карт с реальными цифрами: сколько ₸ вернётся именно вам в месяц и в год' },
    ],
    cashbackBanksLabel: 'Банки в базе анализа',
    cashbackTableHeaders: ['Санат', 'Шығын', 'Үздік карта', 'Кэшбэк'],
    cashbackCta: 'Проверить мой кэшбек →',
    cashbackCtaSub: 'Работает по вашим реальным транзакциям',

    // ── RegisterModal ──
    regTitle: 'Попробовать Finvy',
    bizBadge: 'Финансовые отчёты без ручной сборки',
    bizDesc: 'Finvy собирает операции, категории и движение денег в понятный управленческий отчёт для собственника.',
    bizFeatures: [['Cash Flow', 'готов сразу'], ['P&L', 'по категориям'], ['PDF', 'для отчетности']],
    bizProfit: 'Прибыль',
    bizReport: 'Отчёт',
    regLoginTitle: 'С возвращением',
    regAlready: 'Уже есть аккаунт?',
    regNoAccount: 'Нет аккаунта?',
    regLogIn: 'Войти',
    regSignUp: 'Зарегистрироваться',
    regEmail: 'Ваш email',
    regPassword: 'Придумайте пароль',
    regPhone: 'Ваш номер телефона',
    regContinue: 'Продолжить',
    regCreating: 'Создаём аккаунт…',
    regLoggingIn: 'Входим…',
    regOr: 'или',
    regErrEmail: 'Введите корректный email',
    regErrPassword: 'Минимум 6 символов',
    regErrPhone: 'Введите номер телефона',
    regSetupTitle: 'Настроим',
    regSetupTitleEnd: 'для вашего бизнеса',
    regCompany: 'Название компании',
    regIndustry: 'Выберите отрасль',
    regIndustries: ['IT и ПО', 'Интернет-магазин', 'Розничная торговля', 'Услуги', 'Строительство', 'Медицина', 'Другое'],
    regTeamSize: 'Размер команды',
    regSizes: ['1 (только я)', '2–5', '6–20', '21–50', '51+'],
    regStartTrial: 'Начать',
    regDoneTitle: 'Всё готово!',
    regDoneSub: 'Ваш аккаунт готов.',
    regDoneSub2: 'Ваши счета готовы к работе.',
    regGoDashboard: 'Перейти в дашборд →',
    regBenefits: [
      'Вы контролируете расходы и избегаете кассовых разрывов',
      'Вы знаете, что приносит прибыль, а что съедает бюджет',
      'Вы планируете платежи заранее и спите спокойнее',
      'Вы принимаете решения на основе цифр, а не интуиции',
      'Вы работаете комфортно — один или с командой (бухгалтером)',
    ],
    regLeftTitle: 'управлять финансами бизнеса легко',
    regLeftSub: '😊 на самом деле можно',
    regStudentQ: 'Вы студент?',
    regYes: 'Да',
    regNo: 'Нет',
    regRevenueQ: 'Примерный месячный оборот',
    regRevenues: ['до 500 000 ₸', '500 000 – 2 млн ₸', '2 – 10 млн ₸', '10 – 50 млн ₸', '50+ млн ₸'],
    regBanksQ: 'Какие банки используете?',
    regExpensesQ: 'Основные статьи расходов',
    regExpenseTypes: ['Зарплата', 'Аренда', 'Реклама', 'Закуп товаров', 'Логистика', 'Связь/IT', 'Налоги', 'Другое'],
  },

  kz: {
    menu: 'Мәзір',
    navLinks: [
      { label: 'Мүмкіндіктер', href: '#features' },
      { label: 'Жұмыс істеу принципі', href: '#how-it-works' },
      { label: 'Кімге арналған', href: '#for-business' },
      { label: 'Тарифтер', href: '#pricing' },
    ],
    signUp: 'Қазір көру',
    myAccount: 'Жеке кабинет',
    heroTag: '✦ Қазақстанға арналған ақылды қаржы',
    heroTitle: 'Қаржыңызды толық бақылауға алыңыз',
    heroTitleLine1: 'Қаржыңызды',
    heroTitleLine2: 'толық бақылауға алыңыз',
    heroSub: 'Толық бақылауға ие болыңыз: AI-аналитика жазбаларыңызды дәл болжамдарға айналдырады және басқару бойынша кеңес береді. Көрнекі графиктер, төлем күнтізбесі және дербестендіру — қаржылық көріністі толық көріп, болашағыңызды сеніммен жоспарлаңыз.',
    heroTrust1: '11 ҚР банкі',
    heroTrust2: 'Банктік шифрлау',
    heroTrust3: '3 минуттық баптау',
    tryFree: 'Қазір көру',
    freeBadge: 'Жылдам старт',
    freeDemo: 'Қалай жұмыс істейтінін көру',
    demoBadge: '2 мин',
    googleRating: 'Google рейтингі',
    trialNote: 'Қолмен енгізуден немесе банк үзіндісін жүктеуден бастаңыз',
    forecastSubtitle: 'Қаржылық болжам',
    analyticsSubtitle: '24/7 аналитика',
    reportsSubtitle: 'PDF есептер',
    featTitle: 'Finvy — сіздің жеке және бизнес қаржыңыздың тыныштығы',
    featSub: 'Кестелер мен болжамдарды ұмытыңыз — қарапайым онлайн құралдың көмегімен қаржыңызды толық бақылауға алыңыз. Ақша ағынын қадағалаңыз және ақшаның қайда кетіп жатқанын әрқашан біліп отырыңыз',
    aiCopTitle: 'AI-ассистент Finvy',
    aiCopNew: 'Жаңа',
    aiCopSub: 'Сіздің жеке және бизнес қаржыңызға арналған жеке AI-көмекшіңіз',
    aiMonthly: 'Ай сайынғы есептер',
    aiMonthlyDesc: 'Кірістер мен шығыстарды егжей-тегжейлі талдайтын ай сайынғы PDF есебін алыңыз',
    aiInsights: 'Қаржылық инсайттар',
    aiInsightsDesc: 'Нақты деректер негізіндегі шығындарыңыз бен болжамдарыңызды AI арқылы талдау',
    aiAlerts: 'Ақылды хабарландырулар',
    aiAlertsDesc: 'Кассалық алшақтықтар туындағанға дейінгі проактивті хабарландырулар',
    withoutApp: 'Finvy-сіз',
    withApp: 'Finvy-мен',
    integrationsCount: '',
    integrationsSub: '',
    integrationsAlso: 'Сондай-ақ',
    integrationsApiDesc: 'Сіздің міндеттеріңізге сәйкес үздіксіз интеграцияға арналған жеке API кіреді',
    featAnalTag: 'Аналитика',
    featAnalTitle: 'Икемді қаржылық басқару',
    featAnalDesc: 'Қаржылық хаос туралы ұмытыңыз. Кіріс пен шығыс санаттарын реттеңіз, ақша ағынын басқарыңыз және не жұмыс істейтінін, ал не бюджетті жеп жатқанын әрқашан біліңіз.',
    featCalTag: 'Күнтізбе',
    featCalTitle: 'Төлемдер мен түсімдерді басқарыңыз',
    featCalDesc: 'Ақша жоғалмайды — ол не сіз үшін жұмыс істейді, не сіз оны жоғалтасыз. Finvy қаржылық теңгерімді бақылауда ұстауға көмектеседі.',
    problems: [
      { icon: '📊', title: 'Қаржыны кестелерде жүргізесіз', desc: 'Excel-дегі есептеулер уақытты алады hardware және қателіктер қаупін арттырады' },
      { icon: '👁', title: 'Чектер, қарыздар мен жазбалар — бірдеңе ескерусіз қалады', desc: 'Маңызды төлемдер назардан тыс қалуы мүмкін' },
      { icon: '📈', title: 'Бухгалтер бар, бірақ толық бақылау жоқ', desc: 'Жобалардың тиімділігі мен кассалық алшақтықтар туралы кеш білесіз' },
      { icon: '👥', title: 'Команда қаржыны басқаруға тартылмаған', desc: 'Маңызды төлемдер байқалмай қалуы мүмкін' },
      { icon: '💰', title: 'Кассалық алшақтықтар бизнеске соққы береді', desc: 'Болжам болмағандықтан, тіпті маңызды шығындарға да ақша болмайды' },
    ],
    solutions: [
      { icon: '🧮', title: 'Жобалар, клиенттер, кіріс көздері бойынша қарапайым аналитика — бәрі бір қарағанда түсінікті' },
      { icon: '📁', title: 'Ешқандай өткізіп алған чектер мен қарыздар жоқ', desc: 'Әрбір транзакция бірыңғай жүйеде бақылауда' },
      { icon: '🔄', title: 'Қаржылық деректер әрқашан өзекті, 24/7', desc: 'Банктерден автоматты түрде жүктеу және нақты уақыт режимінде синхрондау' },
      { icon: '💰', title: 'Жеке және бизнес қаржысын бірге басқарыңыз', desc: 'Барлық кірістер мен шығыстарды толық бақылауға арналған бірыңғай жүйе' },
      { icon: '🔔', title: 'Кассалық алшақтықтар туралы проактивті хабарландырулар', desc: 'Finvy ақша ағынын болжайды және тәуекелдер туралы алдын ала ескертеді' },
    ],
    howTitle: 'Қалай жұмыс істейді?',
    howSub: 'Бизнесіңіздің түрі немесе жеке қаржыңызды қалай басқаратыныңыз маңызды емес — егер кірістер мен шығыстар болса, Finvy оларды қадағалауға және басқаруға көмектеседі',
    stepLabel: 'Қадам',
    steps: [
      { title: 'Кірістер мен шығыстарды қолмен немесе дауыспен қосыңыз', desc: 'Транзакцияларды интерфейс, Telegram-бот немесе дауыстық хабарлама арқылы жылдам енгізу — ыңғайлы жолды таңдаңыз.' },
      { title: 'Барлық транзакциялар бір жерде — нақты уақыт режимінде', desc: 'Кірістер мен шығыстар бірыңғай жүйеге жиналады. Қаржының ағымдағы күйін әрқашан көресіз.' },
      { title: 'Толық бақылау: ақша ағыны, P&L және баланс', desc: 'Бизнес пен жеке қаржының толық қаржылық көрінісін көресіз: ақша қайдан келеді және қайда кетеді.' },
      { title: 'Деректеріңіз қауіпсіздікте', desc: 'Барлық қаржылық деректер шифрланған және қорғалған серверлерде сақталады. Қатынас тек сізде.' },
      { title: 'Тұрақты қолдау және сарапшылық кеңестер', desc: 'Көмек керек пе? Біздің команда Finvy-ді сіздің жеке және бизнес қаржыңызға сәйкес баптауға әрқашан дайын.' },
      { title: 'AI-ассистент қаржыңызды талдайды', desc: 'Жасанды интеллекттің арқасында жеке ұсыныстар, болжамдар мен инсайттар алыңыз.' },
    ],
    liveTitle: 'Бәрін тікелей көргіңіз келе ме?',
    liveSub: 'Алғашқы жұмыс кабинетін баптауға көмектесеміз',
    liveBtn: 'Finvy-ді іс жүзінде көру',
    liveBtnBadge: 'СТАРТ',
    stats: [
      { value: '54', label: 'Бизнестер Finvy-мен қаржысын басқаратын елдер', icon: '🌐' },
      { value: '94%', label: 'Клиенттер бізді әріптестері мен серіктестеріне ұсынады', icon: '💬' },
      { value: '100+', label: 'Бизнес секторлары', icon: '🔵' },
    ],
    trustedTitle: 'Бізге бүкіл әлем бойынша дамып келе жатқан компаниялар сенеді',
    trustedSub: 'Қаржысын Finvy-мен басқаратын компанияларға қосылыңыз',
    supportTitle: 'Біз сізді әр қадамда қолдаймыз',
    supportMobile: 'Мобильді қосымша',
    supportMobileSub: 'iOS және Android',
    supportChat: '24/7 чат',
    supportChatSub: 'Telegram және WhatsApp',
    supportConsult: 'Сарапшылық кеңестер',
    supportConsultSub: 'Жеке онбординг',
    bizTitle: 'Қаржыны бақылауға алыңыз — ертең пайданы көресіз',
    bizSub: 'Қолмен немесе дауыспен басқарыңыз. Шығындарды кез келген уақытта енгізіңіз,\nFinvy оларды санаттарға бөліп, нақты көріністі көрсетеді — әрқашан өзекті, 24/7',
    businesses: ['IT және әзірлеу', 'E-commerce', 'Ритейл', 'Қызметтер', 'Құрылыс', 'Медицина', 'HoReCa', 'Білім беру', 'Өндіріс', 'Логистика', 'Маркетинг', 'Жылжымайтын мүлік'],
    bizCTA: 'Cash Flow + P&L 3 күнде емес,\n3 минутта дайын болады',
    bizBtn: 'Қазір көру',
    bizFeatures: [['Cash Flow', 'бірден дайын'], ['P&L', 'санаттар бойынша'], ['PDF', 'есептілік үшін']],
    bizChartYear: 'Ағымдағы жылға',
    bizChartCat: 'Санаттар бойынша ▾',
    bizChartLines: 'Аударымдар ▾',
    vs1cBadge: 'Салыстыру',
    vs1cTitle: 'Finvy vs',
    vs1cSub: '1С бухгалтерлер мен салық комитетіне арналған. Finvy — ақшаны осында және қазір басқаруы керек иелерге арналған.',
    vs1cParam: 'Параметр',
    vs1cFinvy: 'Finvy',
    vs1cRows: [
      { aspect: 'Бағасы', Finvy: '0 ₸-ден бастап — тегін жоспар бар', onec: '40 000 ₽-ден бастап + енгізу + қолдау' },
      { aspect: 'Жұмысты бастау', Finvy: '5 минутта дайын — тіркеліп, бастаңыз', onec: 'Орнатуға, баптауға және оқытуға апталар кетеді' },
      { aspect: 'Қатынау', Finvy: 'Браузер, телефон, планшет — кез келген жерде', onec: 'Нақты компьютерге / серверге байланған' },
      { aspect: 'Жаңартулар', Finvy: 'Автоматты түрде, сіздің қатысуыңызсыз', onec: 'Ақылы, IT-маманды қажет етеді' },
      { aspect: 'Фокус', Finvy: 'Басқару есебі: ақша, пайда, кассалық алшақтықтар', onec: 'Бухгалтерия мен салықтар — операциялық шешімдерге арналмаған' },
      { aspect: 'Аналитика жылдамдығы', Finvy: '30 секундта толық көрініс', onec: 'Есептер бірнеше сағат бойы жасалады, бухгалтерді қажет етеді' },
      { aspect: 'Командалық жұмыс', Finvy: 'Рөлдік қатынас, бәрі нақты уақыт режимінде', onec: 'Бір жұмыс орны немесе қымбат желілік нұсқа' },
      { aspect: 'AI-ассистент', Finvy: 'Кіріктірілген — деректерді талдайды және кеңес береді', onec: 'Жоқ' },
      { aspect: 'IT / бухгалтер керек пе', Finvy: 'Жоқ — кез келген қызметкер игере алады', onec: 'Иә — мамансыз мүмкін емес' },
    ],
    vs1cSwitchCTA: '5 минутта Finvy-ге өтіңіз',
    vs1cSwitchSub: 'Ешқандай орнатулар, IT-мамандар және күрделі баптаулар жоқ',
    vs1cBtn: 'Қазір көру →',
    pricingTitle: 'Ағымдағы тарифтер',
    pricingSub: 'Сәйкес жоспарды таңдаңыз.\nҚолмен енгізуден немесе банк үзіндісін жүктеуден бастаңыз',
    monthly: 'Ай сайын',
    halfYear: 'Жарты жыл',
    annually: 'Жыл сайын',
    mostPopular: 'Танымал',
    perMonth: '/ ай',
    firstFree: 'Жұмысты бастау',
    pricingCustom: 'Келісімді',
    pricingFree: 'Тегін',
    additionalTitle: 'Қосымша сервистермен\nтиімділікті арттырыңыз',
    additionalServices: [
      { icon: '🏦', title: 'Банкпен интеграция*', price: '1 500 ₸ / ай', note: '* Транзакцияларды автоматты түрде импорттау үшін банктік шотты қосыңыз. Операциялар, теңгерімдер және шот деректері Open Banking API арқылы нақты уақыт режимінде синхрондалады.' },
      { icon: '🔗', title: '1С, Excel, CSV, PDF-тен импорттау', price: '1 500 ₸ / ай', note: 'Қаржылық деректерді 1С, Excel, Google Sheets немесе банк үзінділерінен (CSV/PDF) Finvy-ге бірнеше рет басу арқылы тасымалдаңыз.' },
      { icon: '📊', title: 'Cash Flow болжамы', price: '2 500 ₸ / ай', note: 'Транзакциялар тарихы негізінде 30/60/90 күнге арналған AI-ақша ағынының болжамы.' },
    ],
    plans: [
      { name: 'Starter', monthly: 4500, half: 3800, annual: 3500, cta: 'Жұмысты бастау', desc: 'Жаңа бастаушыларға арналған', features: ['4 пайдаланушы', 'Cash Flow есебі', 'Telegram-бот', 'Тек AI-қолдау'] },
      { name: 'Business', monthly: 9000, half: 7500, annual: 7000, cta: 'Жұмысты бастау', desc: 'Шағын командаларға арналған', highlight: true, features: ['6 пайдаланушы', 'Шектеусіз Cash Flow + P&L', 'Telegram-бот', 'AI + қолдау чаты'] },
      { name: 'Корпоративтік', monthly: null, half: null, annual: null, cta: 'Байланысу', desc: 'Ірі бизнеске арналған', features: ['Шектеусіз пайдаланушылар', 'Барлық есептер + кеңейтілген аналитика', 'Басымдықты қолдау', 'Жеке менеджер', 'Жеке интеграциялар'] },
    ],
    reviewsTitle: 'Клиенттеріміз не дейді',
    reviews: [
      { name: 'Александр М.', company: 'IT-компания, 15 адам', text: 'Ақыры біздің бизнес үшін шынымен жұмыс істейтін құрал таптым. Барлық ақша ағындарын нақты уақыт режимінде көріп отырмыз — байқалмаған шығындардан ақша жоғалтуды тоқтаттық.', rating: 5 },
      { name: 'Мария К.', company: 'Интернет-дүкен', text: 'Бір кеште баптап алдым. Енді ақшаның қайда кетіп жатқанын әрқашан білемін. Тек банкпен автоматты синхрондаудың өзі аптасына бірнеше сағатты үнемдейді.', rating: 5 },
      { name: 'Денис Р.', company: 'Құрылыс бизнесі', text: 'Бір уақытта 12 жоба жүргіземіз. Finvy әрқайсысының тиімділігін қадағалауға көмектеседі. Қолдау көрсету командасы өте жақсы.', rating: 5 },
      { name: 'Ольга Т.', company: 'Маркетингтік агенттік', text: 'Бірнеше жылдан кейін кестелерден көштік. Игеру өте оңай, ал уақытты үнемдеу — орасан зор. Кез келген кәсіпкерге ұсынамын.', rating: 5 },
    ],
    readyTitle: 'Қаржыңызды бақылауға алуға дайынсыз ба?',
    bookDemo: 'Баптауды бастау',
    trialNote2: 'Кабинет жасаңыз және алғашқы нақты деректерді қосыңыз',
    footerDesc: 'Бизнеске арналған ақша ағынын басқару бағдарламасы. Қаржыңызды бүгіннен бастап бақылауға алыңыз.',
    footerLinkTitles: { Product: 'Өнім', Company: 'Компания', Support: 'Қолдау', Legal: 'Құқықтық' },
    footerLinks: {
      Product: ['Мүмкіндіктер', 'Тарифтер', 'Жұмыс істеу принципі', 'Интеграциялар', 'Қауіпсіздік', 'API'],
      Company: ['Біз туралы', 'Блог', 'Вакансиялар', 'Пресса', 'Серіктестер'],
      Support: ['Анықтама орталығы', 'Контактілер', 'Күйі', 'Қоғамдастық', 'Жаңартулар'],
      Legal: ['Құпиялылық саясаты', 'Пайдалану шарттары', 'Cookie', 'GDPR'],
    },
    copyright: '© 2025 Finvy. Барлық құқықтар қорғалған.',

    appDemoTitle: 'Ол қалай жұмыс істейді?',
    appDemoSub: 'Барлық шоттарыңыз бен транзакцияларыңыз бір жерде',
    appDemoBusiness: 'Бизнес',
    appDemoIncome: '+ Кіріс',
    appDemoExpense: '− Шығыс',
    appDemoTransfer: '⇄ Аударым',
    appDemoTotal: 'Шоттардағы жалпы сома',
    appDemoMyAccounts: 'Менің шоттарым',
    appDemoTabs: ['Транзакциялар', 'Аналитика', 'Күнтізбе', 'Пайдаланушылар', 'Шоттар', 'Автоережелер'],
    appDemoHeaders: ['Күні', 'Сома', 'Шот/баланс', 'Контрагент', 'Санат', 'Пікір'],
    appDemoAllTime: 'Барлық уақыт',
    appDemoSearch: 'Шоттар, контрагенттер, пікірлер бойынша іздеу',
    appDemoSum: 'Сома',
    appDemoFrom: 'Бастап',
    appDemoTo: 'Дейін',
    appDemoFilter: 'Сүзгі',
    appDemoFutureTx: 'Алдын ала транзакциялар • 95',
    appDemoSet: 'Орнату',
    appDemoAccBank: 'Банк картасы',
    appDemoAccCash: 'Қолма-қол ақша',
    appDemoAccDebit: 'Дебеттік карта',
    appDemoAccReserve: 'Резервтік қор',
    appDemoCatMusic: 'Музыка және шаралар',
    appDemoCatEquip: 'Жабдықты сату',
    appDemoCatOther: 'Басқа шығыстар',
    appDemoCmtSocial: 'Әлеуметтік қолдау',
    appDemoCatSales: 'Сату',
    appDemoCatSalary: 'Жалақы',
    appDemoCatServices: 'Қызметтер',
    appDemoCatComm: 'Байланыс',
    appDemoCatRent: 'Жалдау',
    appDemoCmtRent: 'Наурыз 2026',

    heroAiActive: 'Белсенді',
    heroAiFound: 'пайдаланылмаған кэшбэк табылды',
    heroAiTip: 'Kaspi Business → жалақыны Freedom Bank-ке аударыңыз',
    heroAiApply: 'Оңтайландыруды қолдану',

    cashbackSectionTag: '✦ Жаңа функция',
    cashbackSectionTitle: 'Қате кэшбэк арқылы қанша жоғалтып жатқаныңызды біліңіз',
    cashbackSectionSub: 'ҚР-дағы ешбір қосымша барлық банктердің кэшбэгін бір уақытта салыстырмайды. Finvy әр дүкенде қай картамен төлеу керектігін көрсетеді — және сізге',
    cashbackSectionSubHighlight: '15 000 ₸/ай',
    cashbackSectionSubEnd: 'дейін үнемдеуге көмектеседі. Үзіндіні жүктеп, әлеуетті үнемдеуіңізді көріңіз.',
    cashbackStats: [
      { value: '11', label: 'Базадағы банктер', sub: 'Кэшбэгі бар 20 карта' },
      { value: '37%', label: 'Макс. кэшбэк', sub: 'Банк серіктестерінде' },
      { value: '144K ₸', label: 'Жылдық орташа пайда', sub: 'Типтік шығындарда' },
      { value: '3 мин', label: 'Есепті жасау', sub: 'Кезеңді таңдаңыз → ұсыныс алыңыз' },
    ],
    cashbackExampleTitle: 'Мысалы: сіздің бір айдағы шығындарыңыз',
    cashbackExampleRows: [
      { cat: '🛒 Азық-түлік', spend: '80 000 ₸', best: 'HomeCard Lite', pct: '10%', earn: '8 000 ₸' },
      { cat: '⛽ Жанармай', spend: '30 000 ₸', best: 'HomeCard Lite', pct: '10%', earn: '3 000 ₸' },
      { cat: '🍽 Мейрамханалар', spend: '25 000 ₸', best: 'Береке ALL IN Premium', pct: '8%', earn: '2 000 ₸' },
      { cat: '🚕 Такси', spend: '15 000 ₸', best: 'Береке ALL IN Premium', pct: '15%', earn: '2 250 ₸' },
    ],
    cashbackExampleTotal: 'Айына кэшбэк',
    cashbackExampleYear: 'Жылына',
    cashbackSteps: [
      { icon: '📊', title: 'Транзакцияларды қосамыз', desc: 'Жүйе санаттар бойынша нақты шығындарыңызды көреді — азық-түлік, такси, ЖҚС, мейрамханалар және т.б.' },
      { icon: '🏦', title: '11 банкпен салыстырамыз', desc: 'Жүйе барлық банктердің кэшбэк бағдарламаларын талдайды және шығындарыңыз бойынша нақты пайданы есептейді' },
      { icon: '💳', title: 'Жеке есеп аласыз', desc: 'Нақты цифрлары бар үздік карталарды көресіз: айына және жылына дәл сізге қанша ₸ қайтарылады' },
    ],
    cashbackBanksLabel: 'Талдау базасындағы банктер',
    cashbackTableHeaders: ['Санат', 'Шығын', 'Үздік карта', 'Кэшбэк'],
    cashbackCta: 'Кэшбэгімді тексеру →',
    cashbackCtaSub: 'Нақты транзакцияларыңыз бойынша жұмыс істейді',

    // ── RegisterModal ──
    regTitle: 'Finvy-ді көру',
    bizBadge: 'Қолмен жинаусыз қаржылық есептер',
    bizDesc: 'Finvy операцияларды, санаттарды және ақша қозғалысын иесі үшін түсінікті басқару есебіне жинайды.',
    bizFeatures: [['Cash Flow', 'бірден дайын'], ['P&L', 'санаттар бойынша'], ['PDF', 'есептілік үшін']],
    bizProfit: 'Пайда',
    bizReport: 'Есеп',
    regLoginTitle: 'Қайта оралуыңызбен',
    regAlready: 'Аккаунтыңыз бар ма?',
    regNoAccount: 'Аккаунт жоқ па?',
    regLogIn: 'Кіру',
    regSignUp: 'Тіркелу',
    regEmail: 'Сіздің email',
    regPassword: 'Құпия сөз ойлап табыңыз',
    regPhone: 'Телефон нөміріңіз',
    regContinue: 'Жалғастыру',
    regCreating: 'Аккаунт жасалуда…',
    regLoggingIn: 'Кіруде…',
    regOr: 'немесе',
    regErrEmail: 'Дұрыс email енгізіңіз',
    regErrPassword: 'Кемінде 6 таңба',
    regErrPhone: 'Телефон нөмірін енгізіңіз',
    regSetupTitle: 'Баптайық',
    regSetupTitleEnd: 'сіздің бизнесіңіз үшін',
    regCompany: 'Компания атауы',
    regIndustry: 'Саланы таңдаңыз',
    regIndustries: ['IT және ПО', 'Интернет-дүкен', 'Бөлшек сауда', 'Қызметтер', 'Құрылыс', 'Медицина', 'Басқа'],
    regTeamSize: 'Команда мөлшері',
    regSizes: ['1 (тек мен)', '2–5', '6–20', '21–50', '51+'],
    regStartTrial: 'Бастау',
    regDoneTitle: 'Бәрі дайын!',
    regDoneSub: 'Аккаунтыңыз дайын.',
    regDoneSub2: 'Шоттарыңыз жұмысқа дайын.',
    regGoDashboard: 'Дашбордқа өту →',
    regBenefits: [
      'Шығындарды бақылайсыз және кассалық алшақтықтардан аулақ боласыз',
      'Не пайда әкелетінін, ал не бюджетті жеп жатқанын білесіз',
      'Төлемдерді алдын ала жоспарлайсыз және тыныш ұйықтайсыз',
      'Шешімдерді түйсікке емес, цифрларға сүйене отырып қабылдайсыз',
      'Ыңғайлы жұмыс істейсіз — жалғыз немесе командамен (бухгалтермен)',
    ],
    regLeftTitle: 'бизнес қаржысын басқару оңай',
    regLeftSub: '😊 шын мәнінде бәрін басқаруға болады',
    regStudentQ: 'Сіз студентсіз бе?',
    regYes: 'Иә',
    regNo: 'Жоқ',
    regRevenueQ: 'Шамамен айлық айналым',
    regRevenues: ['500 000 ₸ дейін', '500 000 – 2 млн ₸', '2 – 10 млн ₸', '10 – 50 млн ₸', '50+ млн ₸'],
    regBanksQ: 'Қай банктерді пайдаланасыз?',
    regExpensesQ: 'Негізгі шығыс баптары',
    regExpenseTypes: ['Жалақы', 'Жалдау', 'Жарнама', 'Тауарларды сатып алу', 'Логистика', 'Байланыс/IT', 'Салықтар', 'Басқа'],
  },
}

// ─────────────────────────────────────────────────────────────────────────────
const LanguageContext = createContext()

const VALID_LANGS = ['en', 'ru', 'kz']

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    const saved = localStorage.getItem('finmap_lang') || 'ru'
    return VALID_LANGS.includes(saved) ? saved : 'ru'
  })

  const changeLang = (code) => {
    setLang(code)
    localStorage.setItem('finmap_lang', code)
  }

  const t = translations[lang] || translations.en

  return (
    <LanguageContext.Provider value={{ lang, changeLang, t, LANGS }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  return useContext(LanguageContext)
}

export function useLanding() {
  const { lang } = useContext(LanguageContext)
  return landingT[lang] || landingT.en
}
